### PR TITLE
reapply a theme to previous formats

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
todos:
- automate it
- smart match on /format changes
- use the new feature to implement server_time
- what to do about expandos? now they are lost/reevaluated
- fix/hide it from buf.pl
- tighten up code when removing lines (e.g from perl)

cool:
- change nick width on the fly
- test themes

**Comment by vague666** [comment]
Great work! That's a shitload of code you've produced :)

**Comment by ailin-nemui** [comment]
to test, run /scrollback redraw

**Comment by ailin-nemui** [comment]
## discussion from irc
- reimplement glib code, do not require newer glib
- design doesn't work, wastes 2x the memory (instead: need to avoid storing rendered lines)

**Comment by dequis** [comment]
I think a design that only stores a limited, tiny amount of lines also wouldn't need reimplementing glib stuff, as a bunch of strdup wouldn't hurt in that case

**Comment by ailin-nemui** [comment]
superseded by #1079

**Pull request closed without merging**
