### PR TITLE
Make sure witem exists in cmd_cat when using -window

### PR DESCRIPTION
**Pull request by vague666**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@vague666 can you test my change?

**Comment by vague666** [comment]
Works for me, although I'd prefer to print to an itemless window if that's possible, like if item == NULL then Irssi::active_win <-- whatever c code that calls to find a target

**Comment by ailin-nemui** [comment]
then you can maybe change the code to use 
```
if (-window flag is given) {
    printtext_window(active_win, ...);
} else {
    printtext(NULL, NULL, ...);
}
```
?

**Comment by ailin-nemui** [comment]
@irssi/developers

**Pull request merged**
