### PR TITLE
meson build support

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
This will change Irssi to use Meson Build system

Todos:
- capsicum
- otr
- perl
- make dist (?)
- proxy
- double check `-D` directories. do they need `get_option('prefix') /` ?

**Comment by dequis** [comment]
Fun! I guess we're keeping autotools for a while?

**Comment by ailin-nemui** [comment]
I wouldn't keep it too long since we already have not enough people maintaining irssi :D

**Comment by ailin-nemui** [comment]
@irssi/developers please test

**Comment by ailin-nemui** [comment]
short meson manual:

```
meson Build
ninja -C Build
ninja -C Build install
```
| | |
| --- | --- |
| See available options: | `meson configure` |
| Use available options: | `meson Build -Denable-true-color=yes` |
| Change options: | `meson --reconfigure Build -Dwith-proxy=yes` |
| Set prefix: | `meson Build --prefix=$HOME/irssi_inst` |
| Make: | `ninja` |
| Make V=1 | `ninja -v` |
| Make install: | `ninja install` |

**Comment by ailin-nemui** [comment]
I say good enough?

@irssi/developers

**Pull request merged**
