### PR TITLE
Add documents of historical interest

### PR DESCRIPTION
**Pull request by Xe**
- [bigmatix](https://asciinema.org/a/15342)
- EFNet oper guide
- EFNet oper myths
- The Tao of IRC

### CODE REVIEW

**Comment by ahf** [comment]
BIGMATIX <3

**Comment by ahf** [comment]
We can't do this :-(

**Comment by dequis** [comment]
Maybe add a configure time option to selectively install them?

**Comment by Annwenn** [comment]
come on, Travis, come on… !!!!

**Comment by Xe** [comment]
commit updated:
```( ahf (IRC)) no, don't use xz
( ahf (IRC)) i love bigmatix```

**Comment by AppleDash** [comment]
+1, these are important

**Comment by josefnpat** [comment]
While these documents do seem very interesting, I'm not sure that an IRC client repo is the right place to have them.

`irssi` is not a IRC server so I don't know why the `operguide.txt` or the `opermyth.txt` even remotely makes sense.

Don't get me wrong, I have a great interest in the history of software, especially ones as old and as unique as IRC. Perhaps you could host your own site with IRC historical information?

**Comment by dequis** [comment]
Maybe compress `operguide.txt` and `opermyth.txt` with xz

**Comment by ahf** [comment]
I hate to be the party pooper, but we are not going to have these in the irssi tree :-(

**Comment by dequis** [comment]
But operguide.txt and opermyth.txt aren't compressed!

**Comment by GeertHauwaerts** [comment]
Why merge locally and declinde the PR? :p

**Pull request closed without merging**
