### PR TITLE
Don't trigger activity on hidden lines by default

### PR DESCRIPTION
**Pull request by ailin-nemui**
attempt to fix #933

### CODE REVIEW

**Comment by dwfreed** [comment]
activity_hide_level shouldn't have to include HIDDEN, because that ends up being counterintuitive.  It would suggest that whenever a message has HIDDEN level, it would not trigger activity, rather than being based on the window's hidelevel setting.  The hidelevel activity hiding should always happen, and if a user wants to put HIDDEN in their activity_hide_level, then that will always not trigger activity if the message has HIDDEN level, even if window hidelevel would not hide it (eg because it's set to none).

**Comment by ailin-nemui** [comment]
then we don't have a way to trigger activity for hidden things, which is bad imo. for example you may want to hide the joins by default but still see in your Act bar that someone joined

**Comment by dwfreed** [comment]
That's also counterintuitive; people aren't going to want to see activity for a channel and not see anything change in the channel as a result (because of their window hidelevel).  If they cared about the activity, they'd generally care to see it too, so they'd remove that level from their window hidelevel.

**Comment by ailin-nemui** [comment]
@irssi/developers

**Pull request merged**
