### PR TITLE
support config file in XDG style

### PR DESCRIPTION
**Pull request by keis**
A quick and dirty patch that tries to load the config from the xdg configured location. This is not very useful on its own but I figured the best way to open the discussion on xdg in irssi is by putting some code out there.

More on XDG Base Directory http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

### CODE REVIEW

**Comment by wsdjeg** [comment]
I also want irssi support `$XDG_CONFIG_HOME`, as you can see the differences between neovim and vim.

**Comment by Managor** [comment]
Any progress on this issue yet?

**Comment by josteink** [comment]
@Managor: It's probably not the answer you're looking for, but I decided to give [weechat](https://github.com/weechat/weechat) a try, and it supports quite a lot of things irssi doesn't, including this.

**Comment by dequis** [comment]
@josteink in what way does it support this? I have a `~/.weechat` here and googling "weechat xdg" gets me this old issue http://savannah.nongnu.org/task/?10934 which went more or less the same way as every single xdg issue in every project.

FWIW there's always `irssi --home ~/whatever`

**Comment by josteink** [comment]
Oh. Seems you're right and I'm 100% in the wrong. My bad.,

I did type the comment out of memory, and somehow I must have mixed something up.

Consider my comment withdrawn.

**Pull request closed without merging**
