### PR TITLE
Make autoclose_window work when /disconnect'ing

### LINKED ISSUE #508: autoclose_windows ON but windows are still open on /disconnect
When /disconnecting from a server/network, all orphaned windows remain open, even if `autoclose_windows` is set to `ON`

This happens as of irssi 0.8.19 (20160323 0008)
It also happened with 0.8.17 ...

### PR DESCRIPTION
**Pull request by LemonBoy**
I guess it makes sense.
Closes #508.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
not sure about this one I feel like there maye a reason

**Comment by dequis** [comment]
Yeah this is subtle stuff. I wouldn't touch it.

**Comment by ailin-nemui** [comment]
ehm, I meant we should think twice, not cannot touch ;)

**Comment by LemonBoy** [comment]
For reference, [here](https://github.com/LemonBoy/irssi/blob/cf3361e5fdc2b90924519ccc8479b7fcf4e77670/src/fe-common/core/fe-channels.c#L91) is where new bindings for the windows are introduced during the disconnection phase.

**Comment by ailin-nemui** [comment]
one potential use case, leaving windows open so that once you connect again the channels are rejoined there. whereas autoclose_windows' target was the case where /part should close a window without requiring /wc if no items are left

**Comment by LemonBoy** [comment]
Hmm, maybe we could just add a `-kill-win` argument to `/disconnect` ?

**Comment by strk** [comment]
`-kill-win` argument to `/disconnect` sounds like a good start. It would be even better if it could be configured to be the default for `/disconnect` (thus allowing passing a -keep-win).

**Comment by ailin-nemui** [comment]
I will close this and welcome any PR which adds a setting autoclose_windows_on_disconnect (maybe that should also close queries?)

**Pull request closed without merging**
