### PR TITLE
Use full paths to includes

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
This is a huge change, replacing all the #includes with full paths and removing -Is from Makefile.ams

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by ailin-nemui** [comment]
pretty sure it will break them :(

**Comment by dequis** [comment]
rude :(

**Comment by falsovsky** [comment]
For me its OK. Ill update FiSH afterwards. I always thought that irssi includes were weird.

**Comment by elfring** [comment]
Thanks for your improvement of affected include guards.

**Pull request merged**
