### PR TITLE
fix crash on startup when resizing before active_win

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
reported by fling

**Comment by dequis** [comment]
Nice, how did you figure it out? What are the repro steps?

**Comment by ailin-nemui** [comment]
I did
```
while :; do pkill -WINCH irssi; done
```

**Comment by ailin-nemui** [comment]
bdo#935813 @smcv

**Comment by ailin-nemui** [comment]
actually a duplicate of #1053 oops!

**Pull request merged**
