### PR TITLE
Improve the WINDOW help

### PR DESCRIPTION
**Pull request by ailin-nemui**
Properly describe the window command.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@GeertHauwaerts would welcome your review

**Comment by dequis** [comment]
Posting here for reference, sorted diff made by Koffa on #irssi

```diff
-    BALANCE:      Balance the window locations when using split windows.
+    BALANCE:      %|Balance the heights of all split windows.
-    CLOSE:        Closes a window.
+    CLOSE:        %|Closes the current window, the specified one or all windows in the given range.
-    DOWN:         Go to the window below when using split windows.
+    DOWN:         %|Set the split window below the current one active. At the bottom, wraps to the top.
-    GOTO:         Go to the window with the given nickname, channel or number.
+    GOTO:         %|Go to the window with activity, with the given nickname, channel or with the specified number.
-    GROW:         Increase the window size when using split windows.
+    GROW:         %|Increase the size of the active split window by the specified number of lines.
-    HIDE:         Hide the window when using split windows.
+    HIDE:         %|Hides the current split window, or the split window specified by number or item name.
-    HISTORY:      Clears the window history buffer.
+    HISTORY:      %|Set or clear a specific named history to use for this window. All windows with the same named history will share a history.
-    IMMORTAL:     Modifies the window mortality status.
+    IMMORTAL:     %|Modifies or queries the window mortality status. Immortal windows have an extra protection against WINDOW CLOSE.
-    ITEM GOTO:    Go to the specified nickname, channel or window item number.
+    ITEM GOTO:    %|Change to the query with the specified nickname, channel with the given name or window item number.
-    ITEM MOVE:    Move the active window item to another window.
+    ITEM MOVE:    %|Move the active window item to another window, or move the channel or query item specified by their name to the current window.
-    ITEM NEXT:    Go to the next item in the window.
+    ITEM NEXT:    %|Make the next item in this window active.
-    ITEM PREV:    Go to the previous item in the window.
+    ITEM PREV:    %|Make the previous item in this window active.
-    LAST:         Go to the last window.
+    LAST:         %|Go to the previously active window.
-    LEFT:         Go to the previous window.
+    LEFT:         %|Go to the previous window numerically that is part of the current sticky group (or not part of any sticky group).
-    LEVEL:        Modifies the text levels to display in the window.
+    LEVEL:        %|Changes the text levels to display in the window, or query the current level.
-    LIST:         List all the windows.
+    LIST:         %|List all the windows.
-    LOG:          Modifies the logging status.
+    LOG:          %|Turn on or off logging of the active window, optionally specifying the log file to use.
-    LOGFILE:      Modifies the location to the log file.
+    LOGFILE:      %|Sets the location of the log file to use for window logging without starting to log.
-    MOVE DOWN:    Move the window down when using split windows.
+    MOVE DOWN:    %|Move the current window to the sticky group of the split window below. If no sticky group remains, the split window collapses.
-    MOVE FIRST:   Move the window to the first position.
+    MOVE FIRST:   %|Move the window to the first position. Any windows inbetween are moved to their numerically next positions.
-    MOVE LAST:    Move the window to the last position.
+    MOVE LAST:    %|Move the window to the last position. Any windows inbetween are moved to their numerically previous positions.
-    MOVE LEFT:    Move the window to the previous location.
+    MOVE LEFT:    %|Move the window to the numerically previous location inside the current sticky group.
-    MOVE NEXT:    Move the window up.
+    MOVE NEXT:    %|Move the window to the place of the numerically next window. At the last position, move the window to the first position and renumber the consecutive block at first position (if any)
-    MOVE PREV:    Move the window down.
+    MOVE PREV:    %|Move the window to the place of the numerically previous window. At the first position, move the window to the end and renumber the consecutive block that it was part of.
-    MOVE RIGHT:   Move the window to the next location.
+    MOVE RIGHT:   %|Move the window to the numerically next location inside the current sticky group.
-    MOVE UP:      Move the window up when using split windows.
+    MOVE UP:      %|Move the current window to the sticky group of the split window above. If no sticky group remains, the split window collapses.
-    MOVE:         Move the window.
+    MOVE:         %|Move the window to the specified number or the first number that is in use when moving the window in the direction of the specified position. Any windows inbetween are shifted towards the old position of the window (unused positions remain empty)
-    NAME:         Give the window a name.
+    NAME:         %|Change or clear the window name. Window names must be unique.
-    NEW:          Creates a new window.
+    NEW:          %|Creates a new hidden or split window.
-    NEXT:         Go to the next window.
+    NEXT:         %|Go to the next window numerically.
-    NUMBER:       Move the active window to another position.
+    NUMBER:       %|Change the active window number to the specified number, swapping the window already in that place if required. With -sticky, protect the window number from renumbering done by windows_auto_renumber. (To re-set the sticky attribute, use WINDOW NUMBER again without -sticky.)
-    PREVIOUS:     Go to the previous window.
+    PREVIOUS:     %|Go to the previous window numerically.
-    REFNUM:       Go to the window with the given number.
+    REFNUM:       %|Go to the window with the given number.
-    RIGHT:        Go to the next window.
+    RIGHT:        %|Go to the next window numerically that is part of the current sticky group (or not part of any sticky group).
-    SERVER:       Set the active server of the window.
+    SERVER:       %|Change the active server of the window or the server stickyness. If the server is sticky, it cannot be cycled with next_window_item/previous_window_utem
-    SHOW:         Show the window when using split windows.
+    SHOW:         %|Show the window specified by number or item name as a new split windows. It is made sticky when autostick_split_windows is turned on.
-    SHRINK:       Decrease the window size when using split windows.
+    SHRINK:       %|Decrease the size of the active split window by the specified number of lines.
-    SIZE:         Modify the window size when using split windows.
+    SIZE:         %|Set the current split window size to the specified numer of lines.
-    STICK:        Make the window sticky.
+    STICK:        %|Make the currently active window sticky, or stick the window specified by number to the currently visible split window. Or turn off stickyness of the currently active window or the window specified by number.
-    THEME:        Applies a theme to the windows.
+    THEME:        %|Applies or removes a per-window theme.
-    UP:           Go to the window above when using split windows.
+    UP:           %|Set the split window above the current one active. At the top, wraps to the bottom.
```

Also :+1: because why not.

**Comment by GeertHauwaerts** [comment]
The text loos good, and the use of `%|` is something we should do on all the help files.

There's just one issue, the original order of the help was equal to the order of the parameters in `@SYNTAX:window@`

Is there a specific reason you swapped the order of the items?

**Comment by ailin-nemui** [comment]
I ordered it according to *my* `@SYNTAX:window@` ordering, which weirdly has the LOG commands not on top but in the middle. Otherwise the ordering seems to be identical. Maybe the syntax extraction is non-deterministic?

**Comment by dequis** [comment]
Not worth making an extra PR for this, but you can fix that non-determinism with just a sort in `syntax.pl`. I get the `LOG` at the top both with and without the sort.

```diff
diff --git a/syntax.pl b/syntax.pl
index bf10451..33bd12b 100755
--- a/syntax.pl
+++ b/syntax.pl
@@ -10,7 +10,7 @@
 # Remember to include the asterisk ('*').
 $SRC_PATH='src';

-@files = `find src -name '*.c'`;
+@files = sort `find src -name '*.c'`;

 foreach $file (@files) {
    open (FILE, "$file");
```

(debian's reproducible builds guide actually mentions filesystem order as one common problem)

**Comment by ailin-nemui** [comment]
ok @GeertHauwaerts

**Pull request merged**
