### PR TITLE
make default keybinds deletable

### LINKED ISSUE #507: irssi doesn't remember /bind -delete on default build-in keybindings
If you want to unbind a keybind that is build-in in irssi you can use for example:
/bind -delete meta-1

This works, however, after /save  and /quit and restarting irssi, the default binding is back.
Irssi should remember that a certain build in keybind has been unbound.

A workaround can be to put the `/bind -delete` in `~/.irssi/startup` until this bug has been solved

### PR DESCRIPTION
**Pull request by ailin-nemui**
this should fix #507

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@peterleurs if you want you can test it :)

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dequis** [comment]
Hm, this changed a bit since i looked at it, what's new, the -reset thing?

**Comment by ailin-nemui** [comment]
I thought it might be useful to reset something to the default config (before, deleting would mean it was reset to default state after restart)

**Comment by dequis** [comment]
Tested, looks good, `docs/help/in/bind.in` needs a mention of -reset

**Comment by ailin-nemui** [comment]
thanks for review

**Pull request merged**
