### PR TITLE
rewrite how /bind searches for bindings when listing them

### PR DESCRIPTION
**Pull request by vague666**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
what use case is this?

**Comment by vague666** [comment]
When searching it searches from the beginning, so you need to know what you are looking for to find it, would be better to search the same way /set txt finds settings with txt in them

**Comment by ailin-nemui** [comment]
mhm, I guess that's fine. can you change it to strstr instead of g_strrstr though ;p

@irssi/developers  ?

**Comment by ailin-nemui** [comment]
@irssi/developers

**Pull request merged**
