### PR TITLE
Reset the status of the bracketed paste mode on exit

### PR DESCRIPTION
**Pull request by LemonBoy**
Closes (?) #449

### CODE REVIEW

**Comment by ailin-nemui** [comment]
we probably need to do this also on suspend

**Comment by LemonBoy** [comment]
We don't have any way to get the user preference (afair) at suspension-time

**Comment by ailin-nemui** [comment]
we need to keep track of it in the terminal file (static variable). That'll also save us from sending the escape sequence more often than required

**Comment by ailin-nemui** [comment]
(the same approach will be used for toggling the kx bit in the future)

**Pull request closed without merging**
