### PR TITLE
Do not beep if the source of the beep is in activity_hide_targets

### PR DESCRIPTION
**Pull request by wilhelmy**
Here we go again.
Thanks to Nei for pointing out I probably need to resubmit my pull request.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@wilhelmy can you say if dgl's work allows you to achieve your goal and thus makes this patch unneeded?

**Comment by dequis** [comment]
@wilhelmy ping, see above

**Comment by wilhelmy** [comment]
Sorry to keep everybody waiting. Seems to work fine so far.

**Comment by wilhelmy** [comment]
I guess I was a bit too quick with that comment. The bot still beeps, everything else is as expected.
Do I need a newer irssi? I'm running 0.8.17.

**Comment by ailin-nemui** [comment]
@dgl do you know anything?

**Comment by ailin-nemui** [comment]
@wilhelmy this works for me in 0.8.18-beta1, can you confirm?

**Comment by wilhelmy** [comment]
@ailin-nemui how did you test it? Maybe I'm simply doing it wrong?

**Comment by ailin-nemui** [comment]
I think I simply did `/ignore =botnick NO_ACT DCCMSGS` and then it wouldn't beep

**Comment by ailin-nemui** [comment]
@wilhelmy please reopen if this is still an issue

**Pull request closed without merging**
