### PR TITLE
Change a hash lookup so it compiles

### PR DESCRIPTION
**Pull request by pstray**
As instructed by Nei on freenode

### CODE REVIEW

**Comment by dequis** [comment]
My first reaction was "WTF?", turns out that's a function added in glib 2.32, our minimum requirement is 2.6, and travis ci runs 2.32.

It could definitely use a better commit message (`git commit --amend`, edit the message, `git push --force`). I'd suggest "Change g_hash_table_contains() for compatibility with glib < 2.32". Or something.

Other than that, :+1:

**Comment by pstray** [comment]
On Sun, Apr 19, 2015 at 6:36 PM, dx <notifications@github.com> wrote:

> git push --force


done :)


-- 
  Peder Stray

**Comment by dequis** [comment]
I think there was a failed attempt to exit vim there :D

**Comment by pstray** [comment]
Wonder how that got there... :wo isn't exactly something i would write, and
definitly not there :)  Updated now:)


On Sun, Apr 19, 2015 at 11:51 PM, dx <notifications@github.com> wrote:

> I think there was a failed attempt to exit vim there :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/irssi/irssi/pull/241#issuecomment-94318039>.
>



-- 
  Peder Stray

**Comment by ahf** [comment]
LGTM. Thanks a lot :-)

**Pull request merged**
