### PR TITLE
fix autotools build

### PR DESCRIPTION
**Pull request by ailin-nemui**
some missing files due to recent changes

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dequis** [comment]
Uhhh what was broken and how does this fix it?

**Comment by ailin-nemui** [comment]
make dist, one thing that you'd typically not test

**Comment by ailin-nemui** [comment]
some changes needed @dequis ?

**Comment by dequis** [comment]
I think this is alright, the CI stuff is out of scope of this fix

**Pull request merged**
