### PR TITLE
add access to set hidden_level from perl…

### PR DESCRIPTION
**Pull request by vague666**
Requires a $view->redraw to update view

### CODE REVIEW

**Comment by ailin-nemui** [comment]
we need a strategic decision, should we add a lot of setters? I am against it because they don't work like the hash access. and we have Irssi::command. maybe if we would implement hash setters instead, but that needs more code

**Comment by vague666** [comment]
I'm the wrong person to answer that question :)

**Comment by dequis** [comment]
Can't say much here myself, don't really understand the issue. What would this hash access / hash setter stuff look like?

**Comment by ailin-nemui** [comment]
would look like $view->{hidden_level} = MSGLEVEL_...

**Comment by ailin-nemui** [comment]
I will close this for now since I don't like adding more api functions that are better written as Irssi::command. but if someone else disagrees feel free to reopen/merge

**Comment by vague666** [comment]
Time to discuss this too :)
I disagree, the problem is that running the commands with Irssi::command adds complexity to the scripts which can be simplified with api calls
Two examples:
- toggle_hidelevels.pl hooks to 'window hidelevel' command chain so that the script can know when users manually change window hidelevel, since the script toggles hidelevels by calling 'window hidelevel' from the script this has to be taken into account when hooking into the command chain
- away.pl calls 'away' to set/unset away status, it also hooks into the 'away' command chain and in many instances enough care hasn't been taken to take this into account

A way to access the lowlevel setters is the best(easiest) way imo, the hash setters code would be something to look at but XS evades me to a large degree, not enough interest in it to dive in

@irssi/developers

**Pull request closed without merging**
