### PR TITLE
Fix the tab completion for paths starting with ./

### PR DESCRIPTION
**Pull request by LemonBoy**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
which issue exactly does this fix?

I found the following issue:
- /load <tab> - no completion
- /load <tab> with hidden files present, and this patch, - no completion
- /load a<tab> - completes files with a*
- /load .<tab> and this patch, - no completion
- /load .<tab> and this patch, completes ./.*

at least with this patch the no-completion behaviour seems to be more consistent. but I wonder if it shouldn't always go into completion (of all files) in such case?

**Comment by LemonBoy** [comment]
I honestly don't remember anymore.

**Comment by ailin-nemui** [comment]
github ate my `<tab>`s. maybe we can fix it to complete all files if required in that spot?

**Comment by ailin-nemui** [comment]
if you don't have a good explanation for a patch it cannot be merged imo

**Comment by dequis** [comment]
The title is misleading, it makes more sense in the comment in the code:

```
/* Skip the dotfiles unless the user explicitly asked us
 * to do so. Basename might be './', beware of that */
```

And I think there's something mistyped in the comment above, maybe should be:

- `/load <tab>` with this patch, no completion
- `/load <tab>` without this patch, completes to .* (hidden files in the current directory)
- `/load a<tab>`  with or without this patch, completes files with a*
- `/load .<tab>` with this patch, no completion
- `/load .<tab>` without this patch, completes ./.*

Adding to that

- `/load ./<tab>` with this patch, no completion
- `/load ./<tab>` without this patch, completes ./.*

The last one is certainly unexpected - you're referring to the local directory and it completes dotfiles. Same thing with the case of empty input, that's weird

I think this makes sense now.

**Comment by ailin-nemui** [comment]
no idea what this does, I think completion still is less than ideal

**Comment by dequis** [comment]
yolomerge

**Pull request merged**
