### PR TITLE
improve nicklist performance

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
this was mentioned by someone on IRC

**Comment by ailin-nemui** [comment]
macro or copypasta?

**Comment by LemonBoy** [comment]
Looks vile, I'd suggest writing a new iterator that walks over the hash table values descending into the lovely linked list that is the value.

**Comment by dequis** [comment]
copypasta > macro

**Comment by ailin-nemui** [comment]
there

**Comment by dequis** [comment]
This one was originally reported as high cpu usage when receiving messages in >1000 user channels when there's an ignore that uses the "-replies" argument.

**Pull request merged**
