### PR TITLE
run clang-format as a pull request hook

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by dequis** [comment]
Sup?

**Comment by ailin-nemui** [comment]
not sure how to best go about it. you can check the current state here :  https://github.com/irssi/irssi/pull/1079#partial-pull-merging

what do you think, is failing the  build like that good (enough)?

**Comment by dequis** [comment]
Oh that makes more sense. Yeah, I'd just tweak the output so that the "cat diff" and "cmp" steps are the same (`&&` them together) so if it fails it shows the diff right in the failing step.

Also goddamn the scope of that PR was already scary before

**Comment by ailin-nemui** [comment]
@dequis I think it's ready

**Comment by ailin-nemui** [comment]
let's see how much self inflicted pain that will be!

**Pull request merged**
