### PR TITLE
configure automake with nostdinc

### PR DESCRIPTION
**Pull request by ailin-nemui**
the current directory won't be added to the compiler's -I path

### CODE REVIEW

**Comment by ailin-nemui** [comment]
this makes the build closer to meson. also it means `#include <term.h>` shouldn't include Irssi's own term.h in #1267

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dequis** [comment]
Did you check if this affects known modules? (Should probably include it in release notes as potentially breaking anyway)

**Comment by ailin-nemui** [comment]
as it is only our own compilation, this should not be able to affect 3rd party modules in any way :-)

**Review by dequis — APPROVED** [review]
Oh okay I assumed it'd stop people from #including things in certain ways

**Pull request merged**
