### PR TITLE
Correctly alias 'channel' to '#channel'

### PR DESCRIPTION
**Pull request by LemonBoy**
Solves the other half of #99 (#49.5 ?)

### CODE REVIEW

**Comment by dequis** [comment]
1. God dammit stop fixing what ahf should fix
2. This will change **all** calls to channel_find (including `Irssi::channel_find()` and `$server->channel_find()` from perl) to succeed where they could have failed before.

After inspecting the results of grepping `channel_find` i can't find any obvious consequences of this. Would need something like a command that takes both nicks and channels in the same parameter, and uses the result of `channel_find()` to determine if it's a channel instead of calling `server_ischannel()` before.

At least from the C side, what i've seen so far seems to behave sanely:

```c
	if (server_ischannel(SERVER(server), target))
		item = irc_channel_find(server, target);
	else
		item = irc_query_find(server, target);
```

But this piece of code doesn't even handle user input, it handles *server* input. So probably not even relevant.

The perl side is messier. Some scripts don't even care about checking the null. Many are handlers of channel events. Very few call `$server->ischannel`. Most seem to fail or return if it's null, i haven't seen a single `} else {` that falls back to handling the channel parameter as a nick.

I guess this is probably safe.

**Comment by RichiH** [comment]
@dequis to be fair to @ahf, he is epically useless.

**Comment by ailin-nemui** [comment]
I think we should keep the addition of # IRC-specific

**Comment by LemonBoy** [comment]
@ailin-nemui This is currently being done in `irc_channel_find_server` so it's pretty much limited to IRC only as-is.

WRT script breakage, there was no guarantee that `channel_find` could be used to successfully determine if a given name is a channel or not, I'd just shrug it off and blame the script developers for trying to break the rules.

**Comment by ailin-nemui** [comment]
the code seems fine, I'm still not convinced if this is the best way to do it, would sort of prefer to make it just apply to /join (but that is a generic command so it wouldn't be as straight forward as changing channel_find). Not my call ;-)

**Comment by dequis** [comment]
I think it's okay.

**Comment by LemonBoy** [comment]
Hmm, we're aliasing <name> as #<name> thus potentially shadowing a valid <name>. Can't check atm if `channel_find` is used in such situations but I'd go the safe route and add the check in `cmd_join` (and remove it from the actual join-a-channel code-path).

**Comment by dequis** [comment]
```
19:11 < TheLemonMan> Nei, ahf gave his blessing to #357, let's merge ?
19:15 < dx> 'blessing'
19:15 < dx> he gave a not very enthusiastic 'okay'
19:17 < TheLemonMan> using a meme
19:17 < dx> a stale meme, even
19:17 < dx> shit tier blessing imo
19:19 < TheLemonMan> in jpeg format, full of compression artifacts
19:20 < Nei> sure
19:21 < Xena> Needs more jpg
19:22 < TheLemonMan> print it, scan it, send it as a huge ass uncompressed tiff
```

**Comment by RichiH** [comment]
`shit tier`? I wouldn't expect anything less, or more, from @ahf 

Thanks to everyone else :)

**Pull request merged**
