### PR TITLE
Correctly serialize the window names.

### PR DESCRIPTION
**Pull request by LemonBoy**
Right off the bat, I've just stumbled across #183 before going to bed.
It compiles (yay) but didn't test it (nay), it's a start :tada:

### CODE REVIEW

**Comment by LemonBoy** [comment]
Paging @dequis

**Comment by dequis** [comment]
wot

**Comment by dequis** [comment]
Just tested this, it works.

In case you lost your commit somewhere, https://github.com/LemonBoy/irssi/commit/c190d09a10c37df96b3b9e04e115352abcfb4984

You got "visible_name" and "name" backwards in the commit log though.

**Comment by LemonBoy** [comment]
https://github.com/LemonBoy/irssi/tree/serialize-channel-name

I wasnt 100% sure about the bindings part, but please test this branch, I'll submit a new pr soon if it fixes the problem.

**Comment by dequis** [comment]
The original patch was better, this one creates new windows after doing /layout save, /leave, /join

**Pull request closed without merging**
