### PR TITLE
restore 8bit support in input entry

### LINKED ISSUE #1018: Input line is echoing utf8 chars on non-utf8 terminal
I have a legacy Linux installation that still uses ISO-8859-1 charset. Commit 9072e988194a36186bd98db844b8285e3f37069a causes irssi to erroneously echo utf8 chars to the input line (start irssi, press 'ä' key, irssi outputs 'Ã¤' on the input line, cursor is placed between the two chars) instead of ISO-8859-1. Everything else seems to work fine, with no encoding problems when sending/receiving text from/to IRC channels. Only input line is affected.

### PR DESCRIPTION
**Pull request by ailin-nemui**
This should fix #1018

Regression of #764

Based on patch by @saahriktu

### CODE REVIEW

**Comment by ailin-nemui** [comment]
at least until #671 is finished

**Comment by dequis** [comment]
Kinda weird to check `unichar_isprint` against a character that might not be unicode after all, but i suspect this isn't the only place where that is done. Would be nice to know how to test this.

**Comment by ailin-nemui** [comment]
I agree and I haven't tested this, only followed similar code

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by suiited** [comment]
mute the thread

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
