### PR TITLE
Include commit and if the tree is dirty in builds of -head versions

### PR DESCRIPTION
**Pull request by dgl**
Implements request in #105

### CODE REVIEW

**Comment by ahf** [comment]
Poke? :-)

**Comment by dgl** [comment]
I don't think doing it in `configure.ac` makes sense for us, when we've done -rc releases we've explicitly marked them as such, so likely won't use this to mark dists.

The use I see for it is someone has a git checkout of Irssi and they don't know where it is built from. If we make it use the git revision when `./autogen.sh` is run there could still be doubt (e.g. git pull and then just re-run make without `./autogen.sh`).

**Comment by dequis** [comment]
@ahf sup.

**Comment by ahf** [comment]
Let's get it in! Thanks.

**Pull request merged**
