### PR TITLE
reapply a theme to previous formats

### PR DESCRIPTION
**Pull request by ailin-nemui**
- [x] fix /set hide_colors 
- [x] fix line IDs on perl side
- [x] reimplement the colour stripping in line2text

### CODE REVIEW

**Comment by ailin-nemui** [comment]
another attempt at #1063

**Comment by ailin-nemui** [comment]
- [x] reimplement glib code, do not require newer glib

- [x] design doesn't waste twice the memory, uses cache and original formats

- completely removed the old textbuffer representation ( https://github.com/shabble/irssi-docs/wiki/Notes-256-Colour#textbuffer-encoding )
  - this may have some drawbacks:
    - texts are no longer NUL-safe
    - additional escaping routines would need to be introduced if text is supposed to contain formatting codes
  - benefits
    - one less layer of indirection
    - NUL-terminated strings, no weird issues with cut off UTF8 (although we fixed that)
    - simpler code

- the textbuffer-formats is an extra module, so if we unhook the signals it should go back to the "old way" of storing pre-rendered text

#### Todos

- [ ] differentiate between deleted formats and empty lines
- [ ] fix all the bugs

----

- we should check if the removal of the optimised textbuffer has any visible performance implications

**Comment by vague666** [comment]
first-off: autotools compiled successfully
then, I have a lot of blinking elements after applying the patch
https://vague.se/pastes/2019-08-07_11:41:58_1920x1080_scrot.png
https://vague.se/pastes/2019-08-07_11:42:26_1920x1080_scrot.png
I'll test reapplying themes next

**Comment by vague666** [comment]
`/scrollback redraw` seems to work well, too bad it's not done automatically yet :)

**Comment by ailin-nemui** [comment]
-> under what circumstances would we "want" an automated scrollback redraw?

**Comment by vague666** [comment]
`/set theme` and `/format ....` imo, and `/window theme`
basically in all instances :) 
Maybe control it with a setting

**Comment by ailin-nemui** [comment]
@vague666 now with less blink

**Comment by dequis** [comment]
You kinda got unrelated stuff in this branch. Also, nice.

**Comment by dequis** [comment]
...I guess that's one way to make the changes not unrelated

Seriously though this PR was already massive enough that it's very hard to give it a proper review, adding a bunch of new features on top doesn't help :(

Feel free to have a kitchen sink branch to experiment with, but don't make that this branch. I'd rather aim to get the original feature reviewed and merged.

**Comment by ailin-nemui** [comment]
this now depends on #1089 

the code is mostly split into 3 parts;
-  ripping out the old textbuffer implementation and storing the line texts and formats
-  the expando caching in special-vars
-  the perl code

**Comment by ailin-nemui** [comment]
you should be able to review each commit individually, but  it's still a big hairy lump

for the view_update_line_cache in textbuffer-view.c, it would make sense to review with white-space ignored (?w=1 )

**Comment by ailin-nemui** [comment]
@irssi/developers please test

**Comment by vague666** [comment]
There's some drawing issues
tested with 1079.diff and  Irssi v1.2-dev-522-g991e24fb-dirty and themes https://irssi-import.github.io/themes/elite.theme and https://bitbucket.org/realnot/dirssi/src/master/
type | elite | dirssi
-----|------|-----
patched | elite.theme patched | dirssi.theme patched
unpatched | elite.theme unpatched | dirssi.theme unpatched

Also, I'd still like the scrollback to be redrawn automatically if possible when theme is applied

**Comment by ailin-nemui** [comment]
thank you very much for the detailed report. btw the auto redraw will come, just not in this PR!

**Comment by ailin-nemui** [comment]
I think I fixed dirssi, still need to check elite

**Comment by ailin-nemui** [comment]
now I think that should fix elite

**Comment by vague666** [comment]
Seems to work as expected now with the themes I've tested :)

**Comment by ailin-nemui** [comment]
@irssi/developers last chance to review....

**Pull request merged**
