### PR TITLE
stop cap_sasl

### LINKED ISSUE #279: Do something about cap_sasl.pl conflicting with the new CAP code
>< dx> TheLemonMan: unrelated: did you hear about that bug with cap_sasl.pl and your CAP patch? not sure if you were around
>< dx> it's not really a bug and i don't know what to do about it
>< TheLemon1an> dx, we need a way to play with the CAPs from the perl side
>< dx> yeah, but people with the old version of the script won't have that
>< TheLemon1an> version-based checks :D
> 
> ```
<< CAP LS
<< CAP LS
<< NICK KindOne
<< USER kindone kindone chat.freenode.net :...
>> :holmes.freenode.net NOTICE * :*** Looking up your hostname...
>> :holmes.freenode.net NOTICE * :*** Checking Ident
>> :holmes.freenode.net NOTICE * :*** Couldn't look up your hostname
>> :holmes.freenode.net NOTICE * :*** Got Ident response
>> :holmes.freenode.net CAP * LS :account-notify extended-join identify-msg multi-prefix sasl
<< CAP END
<< CAP REQ :multi-prefix sasl
>> :holmes.freenode.net CAP * LS :account-notify extended-join identify-msg multi-prefix sasl
<< CAP REQ :multi-prefix sasl
>> :holmes.freenode.net 433 * KindOne :Nickname is already in use.
<< NICK KindOne_
>> :holmes.freenode.net CAP * ACK :multi-prefix sasl
<< AUTHENTICATE PLAIN
>> :holmes.freenode.net CAP * ACK :multi-prefix sasl
<< AUTHENTICATE PLAIN
>> AUTHENTICATE +
<< AUTHENTICATE REDACTED_REDACTED_REDACTED
>> :holmes.freenode.net 904 KindOne_ :SASL authentication failed
```

>< dx> it's interesting how this only breaks in freenode, and works fine elsewhere
>< dx> also not really sure how the server keeps registration on hold after receiving CAP END + CAP REQ
>< TheLemon1an> heh, we end the negotiation and the script doesn't know
>< dx> ahf: what do you think about blacklisting cap_sasl.pl by version in irssi git?
>< ahf> by version?
>< ahf> can't we just write it with fat letters in the release announcement that people should stop using it?
>< dx> something like, current version of cap_sasl.pl is 1.10, blacklist everything older than 2.0
>< dx> dunno.
>< TheLemon1an> we should get the SASL part in before saying that
>< ahf> mmmmmmmmm, HMMMM
>< ahf> create a ticket for it, need to figure out if that is what we want

### PR DESCRIPTION
**Pull request by ailin-nemui**
Fixes #279 by unloading cap_sasl. Does not resolve the other issue
(can be done at a later time)

### CODE REVIEW

**Comment by dequis** [comment]
What other issue?

Code looks good.

**Comment by ailin-nemui** [comment]
issue #323

**Comment by dequis** [comment]
Oh. Yeah, later. Feel free to merge this.

**Comment by ailin-nemui** [comment]
I don't like merging my own PR

**Comment by dequis** [comment]
lolk

**Pull request merged**
