### PR TITLE
Disconnect SASL properly in case the sasl module got unloaded from server

### LINKED ISSUE #629: sasl_disconnect_on_failure not effective when server ignores CAP
cf #618

### PR DESCRIPTION
**Pull request by ailin-nemui**
stops from getting on the network when sasl is unavailable

fixes #629

### CODE REVIEW

**Comment by ailin-nemui** [comment]
by the way the disconnect code was in the wrong place (frontend instead of core)

**Comment by LemonBoy** [comment]
So this server pulls the `sasl` cap during the negotiation? What a wild world we live in.
The patch is fine, just a couple of nits:

- `g_hash_table_lookup_extended` can be replaced with `g_hash_table_lookup` since we only care about the key being there
- `cap_supported` cannot be null if we get there

**Comment by ailin-nemui** [comment]
thanks! we can also get there when the server didn't have any CAP

**Comment by ailin-nemui** [comment]
also it seems that we store value NULL so that would create a problem with the non-extended hash table lookup

**Comment by LemonBoy** [comment]
> we can also get there when the server didn't have any CAP

I forgot about ill-behaving servers :)

> also it seems that we store value NULL so that would create a problem with the non-extended hash table lookup

Yup, I also forgot about the missing values!

**Pull request merged**
