### PR TITLE
fix race condition in terminal init

### LINKED ISSUE #450: potential terminal state not reset after 2x suspend
testing with zsh, after suspending irssi 2x with Ctrl+Z, I don't get working Ctrl+C anymore (for example if I then launch cat). Curiously enough it doesn't seem to happen in bash.

### PR DESCRIPTION
**Pull request by ailin-nemui**
remove the tcgetattr call to a single time on irssi load instead of
querying it each time. Fixes #450

### CODE REVIEW

**Comment by ailin-nemui** [comment]
(I hope)

**Comment by LemonBoy** [comment]
I think there's no need to call `terminfo_term_init` again after the kill SIGSTP returns, a strace shows that the terminal settings are applied twice because of that

**Comment by ailin-nemui** [comment]
they may be applied twice because of term_init being called twice, once from the do_redraw sigcont handler https://github.com/irssi/irssi/blob/master/src/fe-text/term-terminfo.c#L91 and once from the kill-stop function https://github.com/irssi/irssi/blob/master/src/fe-text/term-terminfo.c#L610

**Comment by LemonBoy** [comment]
Exactly, and #452 fixes the problem by sending the smcup only (if available) when we resume from the TSTP signal, we save the current state and then the old settings are re-applied in the SIGCNT handler

**Comment by ailin-nemui** [comment]
in that case I wonder if even the smcup of the code in your suggestion from #452 is necessary? if so, why?

**Comment by LemonBoy** [comment]
The smcup saves the terminal window to be re-applied with a rmcup on the next resume/exit

**Comment by ailin-nemui** [comment]
but terminfo_cont (which is run by the sigcont hander) also runs smcup so why do we need to send *that* twice?

**Comment by LemonBoy** [comment]
You're right, upon further inspection I've updated the PR

**Comment by ailin-nemui** [comment]
after discussion on IRC I conclude that we want to have both this and the #452 eventually

**Pull request merged**
