### PR TITLE
Disable printf and fprintf when compiling with SUPPRESS_PRINTF_FALLBACK

### PR DESCRIPTION
**Pull request by josephbisch**
@irssi/developers - please review. This is for fuzzing.

### CODE REVIEW

**Comment by dequis** [comment]
Does this also handle glib stuff?

**Comment by josephbisch** [comment]
No. Glib stuff seems to only be on stderr (maybe???) so I just used `close_fd_mask=2` from libfuzzer to disable that.

Glib themselves use `close_fd_mask=2` for their oss-fuzz fuzzers: https://github.com/google/oss-fuzz/blob/master/projects/glib/fuzz.options.

**Comment by ailin-nemui** [comment]
do we really need this? afaik there's only like 2 calls to printf in the whole irssi

**Comment by josephbisch** [comment]
Without this (combined with close_fd_mask=2) I get output like this:

```
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ::::�::�
NO WINDOWS: -!- ����������
                          ::::�::�
NO WINDOWS: -!- ����������
NO WINDOWS: -!- �����������::����::�
NO WINDOWS: -!- ��������������������shrink
NO WINDOWS: -!- ��������������*��
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ::::�::�
NO WINDOWS: -!- ����������
                          ::::�::�
NO WINDOWS: -!- ����������
NO WINDOWS: -!- �����������::����::�
NO WINDOWS: -!- ��������������������shrink
NO WINDOWS: -!- ��������������*��
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ::::::�
NO WINDOWS: -!- ����������
                          ::::�::�
NO WINDOWS: -!- ����������
NO WINDOWS: -!- �����������::����::�
NO WINDOWS: -!- ��������������������shrinkk
NO WINDOWS: -!- ��������������*��
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ::::::�
NO WINDOWS: -!- ����������
                          ::::�::�
NO WINDOWS: -!- ����������
NO WINDOWS: -!- �����������::����::�
NO WINDOWS: -!- ��������������������shrinkk
NO WINDOWS: -!- ���������������������������������������������������������������������������������������������*��
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ut��h
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ut��h
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ut��h
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ut��h
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ut��h
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ut��h
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
NO WINDOWS: -!- Irssi: Connection to localhost established
NO WINDOWS: -!- ::���;�:�:RRRRRRRRRRRRRRRR����
NO WINDOWS: -!- 
NO WINDOWS: -!- Irssi: Connection lost to localhost
```

With this (but still with close_fd_mask=2) I get just libfuzzer output. No irssi output.

**Comment by ailin-nemui** [comment]
closing for inactivity

**Pull request closed without merging**
