### PR TITLE
irssiproxy: avoid using pointer after freeing it

### PR DESCRIPTION
**Pull request by mauke**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
thanks

**Comment by dequis** [comment]
How/where did this show up as a bug? `g_slist_remove` doesn't access the contents of the passed pointers as far as i know.

**Comment by mauke** [comment]
It doesn't have to dereference it. `free(ptr)` makes the value of `ptr` indeterminate; using it (e.g. by passing it to a function) has undefined behavior.

**Comment by dequis** [comment]
I know, but did anything happen in practice?

**Comment by mauke** [comment]
I never ran the code. I just looked through it.

**Pull request merged**
