### PR TITLE
Add method to hide lines in a view

### PR DESCRIPTION
**Pull request by ailin-nemui**
Initial code for hidden lines.

Usage: /window hidelevel +joins +parts +quits

### CODE REVIEW

**Comment by ailin-nemui** [comment]
first test by kinlo

**Comment by ailin-nemui** [comment]
todo: XS, better code for modification of lines (edit level, edit content?)

**Comment by dequis** [comment]
Sounds good overall, didn't review in depth.

**Comment by ailin-nemui** [comment]
@irssi/developers

**Pull request merged**
