### PR TITLE
try to make sure the server is still good enough to call ischannel when printing netsplit/join

### LINKED ISSUE #819: Segmentation fault in normal usage
This is with irssi 1.1.0.
I'm not sure what is the cause. I wasn't doing anything unusual at the time.

(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000043549f in sig_print_starting ()
#2  0x0000000000488daf in signal_emit_real ()
#3  0x0000000000489319 in signal_emit_id ()
#4  0x000000000044e675 in printformat_module_dest_charargs ()
#5  0x000000000044e6ec in printformat_module_dest_args ()
#6  0x000000000044e85c in printformat_module ()
#7  0x0000000000488daf in signal_emit_real ()
#8  0x000000000048924f in signal_emit ()
#9  0x0000000000483a91 in server_start_connect ()
#10 0x000000000045fb37 in irc_server_connect ()
#11 0x0000000000482e32 in server_connect ()
#12 0x0000000000484de2 in server_reconnect_timeout ()
#13 0x0000779a07e4571f in g_timeout_dispatch () from /usr/pkg/lib/libglib-2.0.so.0
#14 0x0000779a07e44e1f in g_main_context_dispatch () from /usr/pkg/lib/libglib-2.0.so.0
#15 0x0000779a07e45137 in g_main_context_iterate.isra () from /usr/pkg/lib/libglib-2.0.so.0
#16 0x0000779a07e451f3 in g_main_context_iteration () from /usr/pkg/lib/libglib-2.0.so.0
#17 0x0000000000497a5c in main ()

### PR DESCRIPTION
**Pull request by ailin-nemui**
This should fix #819

### CODE REVIEW

**Comment by dequis** [comment]
Continuing https://github.com/irssi/irssi/issues/819#issuecomment-361118986 here:

This throws two warnings:

```
22:47 -!- Irssi: critical ischannel_func: assertion 'data != NULL' failed
22:47 -!- Irssi: Disconnecting from server localhost: [Reconnecting]
22:47 -!- Irssi: critical ischannel_func: assertion 'data != NULL' failed
```

It also seems to not flush pending netsplits like [lemon-netsplit-base][1] does

```
22:47 <@dx|fb> ac off
22:47 <@root> Deactivating all active (re)connections...
22:47 <@root> facebook - Signing off..
22:47 -!- dx|fb [dx3@localhost.localdomain] has joined &bitlbee
```

[lemon-netsplit-base][1] (and #824) looks like this:

```
23:15 <@dx|fb> ac off
23:15 <@root> Deactivating all active (re)connections...
23:15 <@root> facebook - Signing off..
23:15 -!- Netsplit localhost.localdomain <-> facebook.localhost.localdomain quits: +fb-XXXX, +fb-XXXX, +fb-XXXX, +fb-XXXX, +fb-XXXX, +fb-XXXX
23:15 -!- dx|fb [dx3@localhost.localdomain] has joined &bitlbee
```

[1]: https://github.com/dequis/irssi/tree/lemon-netsplit-base

**Comment by ailin-nemui** [comment]
I'm proposing to put this into git (been running it for a while and tested with bitlbee) @irssi/developers

**Comment by dequis** [comment]
So the safer one for 1.1.1, and this one for git? Sounds like a plan.

There's still the issue that this won't flush pending netsplits when quitting, but that's not a big deal. The real question is if the circumstances that lead to netsplits not being flushed on quit (non-null server, null target) can apply to other less situations in the middle of the connection.

**Comment by ailin-nemui** [comment]
in my testing it did flush them, can you double check that? we can also add a server disconnected handler and add an explicit flush, maybe that's better? I'll rebase this tomorrow....

**Comment by ailin-nemui** [comment]
@irssi/developers

**Pull request merged**
