### PR TITLE
Better interaction between reverse-DNS resolution and reconnection.

### LINKED ISSUE #494: Reverse dns-resolution doesn't play well with /reconnect
When the reverse dns resolution is enabled the resolved hostname replaces the original one in the connrec structure, but this doesn't play well with the reconnection commands.
`cmd_reconnect` blindly tries to reconnect to the same server and `sig_reconnect` fails in a similar way (I guess) since `server_setup_find` fails to match the address when comparing it with the list of `setupservers`.

### PR DESCRIPTION
**Pull request by LemonBoy**
Closes #494

### CODE REVIEW

**Comment by ailin-nemui** [comment]
what is the desired behaviour? what is the current behaviour and how does it change after this patch? maybe the connrec rather shouldn't be updated by reverse resolve at all?

**Comment by LemonBoy** [comment]
The desired behaviour is to use the non-resolved address on subsequent reconnections.
I didn't change how the connrec is updated since I wanted to make the patch to be as least invasive as possible.

**Comment by ailin-nemui** [comment]
I think we should better analyse this and fix the underlying design issue (like updating connrec) if that turns out to be the root issue

**Comment by ailin-nemui** [comment]
see #494

**Pull request closed without merging**
