### PR TITLE
Use the 24bit mIRC colour mappings if colors_ansi_24bit is enabled

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
This PR was sponsored by `bl1p`

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dwfreed** [comment]
This uses mod 100, meaning possible indices are 0-99; however, neither mirc_colors nor mirc_colors24 are long enough to have index 99.

**Comment by ailin-nemui** [comment]
I would hope it does... hopefully only the comment is misleading

**Comment by dwfreed** [comment]
I failed at the math; indeed, only the comments are wrong (first line of both has 16, the 7 subsequent lines have 12 each; 16 + 7 * 12 = 100)

**Pull request merged**
