### PR TITLE
[WIP] Add native proxying

### PR DESCRIPTION
**Pull request by bashrc**
Rebased patches from #148 against the current master, in an attempt to get Tor proxying working. This still doesn't appear to resolve onion addresses correctly.

### CODE REVIEW

**Comment by dequis** [comment]
In what way did you do that rebase which also removed all the authorship information from the original commits...? You should rebase again and add that back

**Comment by ailin-nemui** [comment]
Thank you. Please be understanding that this pr cannot proceed unless someone willing and capable of addressing all the issues raised in that thread, though

**Comment by bashrc** [comment]
The original patches wouldn't apply against the current master. I guess there had been just too many changes since they were originally written. So I manually recreated them.

**Comment by ailin-nemui** [comment]
@bashrc  thanks for your contribution. feel free to reopen once you addressed those comments. thanks for your understanding

**Comment by Silur** [comment]
how does this PR progress? how can I help to get this merged?

**Comment by ailin-nemui** [comment]
there is a lot to do, read through the comments in #148 
in general you can help if you can write C code

**Pull request closed without merging**
