### PR TITLE
Some updates for the irssi proxy module

### PR DESCRIPTION
**Pull request by hansnielsen**
I added a few creature comforts to the proxy module.

* Changed the signals slightly so that there is no "proxy client connected" until a user has authenticated with a password
* Made the console output include more useful details and go to the server windows
* Added a toggle to enable / disable the module; on by default to prevent existing user confusion
* Updated documentation

### CODE REVIEW

**Comment by dequis** [comment]
@hansnielsen poke, i believe this is just missing some /help stuff as geert pointed out.

**Comment by hansnielsen** [comment]
Whoops, kinda forgot about this. Added the help file and rebased it against current master.

**Comment by ailin-nemui** [comment]
I'd use formats for the proxy information output instead of hard-coded printfs. It would be possible to toggle the proxy by unloading the module, I guess a toggle is also fine. The command seems a bit misleading, maybe have just `/proxy` to list connected clients? I wonder if a `/proxy disconnect ` kind of command would be nice to have.

**Comment by dequis** [comment]
The comments of #148 (which is about the non-bnc proxy feature, i.e. socks5 and similar) suggest a /proxy command, which would conflict with this one. Maybe rename this one to /irssiproxy to match the setting names?

**Comment by GeertHauwaerts** [comment]
any update on this?

**Comment by dequis** [comment]
Well, @hansnielsen seems to have disappeared from github (last public activity in february).

I wouldn't mind taking over and opening a new PR based on his work.

**Comment by GeertHauwaerts** [comment]
That would be awesome, since this PR is almost finished and just requires some minor tweaking :)

**Comment by dequis** [comment]
Did some stuff the other day, not completely done yet, but submitted #259 to keep track of it, at least.

**Comment by ailin-nemui** [comment]
continued in #259

**Pull request closed without merging**
