### PR TITLE
Add code to support Github Actions

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dequis** [comment]
So, what makes this preferable to travis?

**Comment by ailin-nemui** [comment]
I can't say yet if this will be preferable. But it's always good to have a choice :-)

(besides, travis doesn't open for me anymore in Firefox 68 and I have no idea why)

**Comment by dequis** [comment]
404 here

**Pull request merged**
