### PR TITLE
Added a -date parameter to /lastlog to prepend each row with the ... 

### PR DESCRIPTION
**Pull request by Lohhari**
row's date

### CODE REVIEW

**Comment by dequis** [comment]
Skimmed patch a bit, looks sane. Is this a feature we want, @ahf?

**Comment by dequis** [comment]
@ahf ^

**Comment by ahf** [comment]
At a bar. Prod me tomorrow.

**Comment by dequis** [comment]
@ahf lol

**Comment by ahf** [comment]
Looks nice, thanks!

**Comment by Lohhari** [comment]
Awesome. Thanks @ahf and thanks for your support @dequis :)

**Pull request merged**
