### PR TITLE
Clarify the help for /ignore -time

### PR DESCRIPTION
**Pull request by vague666**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
maybe `<time>` instead of `<str>`? compare https://irssi.org/documentation/help/knockout/

**Comment by vague666** [comment]
Does knockout accept time units or is seconds the only valid unit?

**Comment by ailin-nemui** [comment]
iirc it uses the same "time value" parsing function

**Comment by ailin-nemui** [comment]
they surely can't be caused by fixing the docs ;)

**Comment by ailin-nemui** [comment]
merged into ailin-nemui/irssi#77

**Pull request closed without merging**
