### PR TITLE
Fix syntax on /help SERVER example

### PR DESCRIPTION
**Pull request by or4n**
Fix syntax on /help SERVER resolve issue #519

### CODE REVIEW

**Comment by ailin-nemui** [comment]
thanks

**Comment by dequis** [comment]
Actually that's valid syntax to modify the port of an existing server

**Comment by dequis** [comment]
Eh nevermind this was mentioned in the other ticket. But I don't think this change clarifies that

**Comment by or4n** [comment]
dequis, you're right. Maybe we should add "-port 6667" to /SERVER MODIFY example?

**Comment by ailin-nemui** [comment]
we need to double check if irssi has a bug in not actually allowing to add multiple same named servers with different ports

iirc the syntax is supposed to be /server -modify newport servername oldport, but /server add only supports /server add servername port

maybe server add should also be fixed to accept -port?

**Comment by or4n** [comment]
I tried to add server with same name but different port. Irssi just says "18:15 -!- Irssi: Server orwell.freenode.net saved" but still doesn't do anything. It doesn't modify old entry or add new one.

I think it would be most logical solution to fix server add and then revert this pr.

**Comment by or4n** [comment]
@ailin-nemui I did some more tinkering around and now have branch where server add accept -port (https://github.com/or4n/irssi/tree/server-add-cmd). Do you think I should make PR from that?

**Pull request merged**
