### PR TITLE
fix a crash when trying to append to a NULL line

### PR DESCRIPTION
**Pull request by ailin-nemui**
reported by @vague666

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@irssi/developers 

obscure textbuffer stuff only triggered from scripts

**Comment by dequis** [comment]
What's the reproducer?

**Comment by ailin-nemui** [comment]
```perl
$window->gui_printtext_after(undef, MSGLEVEL_CLIENTNOTICE, "xxx")
```
seen in similar fashion in `buf.pl`

**Comment by vague666** [comment]
The fix helped but I am still having problems with this code:
http://vague.se/pastes/buf.pl
If I switch the print to gui_printtext_after I see the screen update with a bunch of text and then it's cleared, with print the text stays visible on screen, I'd like to know if any of you can reproduce the behavior

**Comment by ailin-nemui** [comment]
did you try scolling up?

**Comment by vague666** [comment]
Can't remember, I'll try it when I get home

**Comment by vague666** [comment]
The view is actually scrolled up or whatcha-ma-call it
How the screen is after /upgrade:
https://vague.se/pastes/2018-03-21_19:53:03_1920x1080_scrot.png
after pgup:
https://vague.se/pastes/2018-03-21_19:53:41_1920x1080_scrot.png

**Comment by vague666** [comment]
Not sure if that behavior is the desired one, I would expect =Upgrade= to be visible and not scrolled up

**Comment by vague666** [comment]
Maybe I don't understand how gui_printtext_after works? If I think a bit about it, it looks like the text is printed from bottom up, is there a function that prints top to bottom?

**Pull request merged**
