### PR TITLE
fix npe on no text from format_get_text_theme_charargs

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
for example during /quit if buffer has already been unloaded

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dequis** [comment]
Is this because of https://github.com/irssi/irssi/pull/1079 ?

**Comment by ailin-nemui** [comment]
yea it's a condition in this new code

**Pull request merged**
