### PR TITLE
disable tls when using -notls

### PR DESCRIPTION
**Pull request by vague666**

### CODE REVIEW

**Comment by vague666** [comment]
hopefully a #730 fix

**Comment by vague666** [comment]
https://github.com/irssi/irssi/pull/1060/files#diff-820acea5c23ba424526175f91ccd42acL153 needs a bit of thought I reckon, not sure how to handle it

**Comment by ailin-nemui** [comment]
I think we should keep these entries and just not use them

**Comment by ailin-nemui** [comment]
we may need to check why they cannot be unset(?)

**Comment by vague666** [comment]
Not sure what you mean

**Comment by ailin-nemui** [comment]
> -tls_capath/-tls_cafile implication.

my requirement: do not unset tls_capath (like you do in this patch), instead, do not enable TLS unless tls or tls_verify is given. That way, you can "keep" the tls_capath setting and only enable/disable the tls for a server, and  do not have to repeat the tls_capath setting when you enable tls again

> Also, there's no way to get rid of -tls_capath/-tls_cafile without editing the config because the empty string is equivalent to not changing it.

this might need to be fixed, so that -tls_capath '' does remove the capath

**Comment by vague666** [comment]
Ok, I've added -tls_capath '' et al so tls options can be removed with empty string
Where should I look to check for use_tls to disable tls options if use_tls is FALSE?
So far I've added a check to https://github.com/irssi/irssi/blob/master/src/core/servers-setup.c#L170
but all the different code paths makes me uncertain in case I am missing something

**Comment by ailin-nemui** [comment]
@vague666 can you check if this is fixed in latest master?

**Pull request closed without merging**
