### PR TITLE
correct wrong function prefixes

### PR DESCRIPTION
**Pull request by ailin-nemui**
- g_input -> i_input
- g_istr -> i_istr
- g_io_channel -> i_io_channel
- g_hash_free_value -> i_hash_free_value
- remove g_free_true
- gslist -> i_slist
- glog_func -> i_log_func

### CODE REVIEW

**Comment by ailin-nemui** [comment]
We were clobbering the GLib prefix. Note，this is a tad annoying change but better to get over with it

**Comment by ailin-nemui** [comment]
Module authors will have to adapt these changes:

```
    [M] 'constant I_INPUT_READ'    {G_INPUT_READ}
    [M] 'constant I_INPUT_WRITE'    {G_INPUT_WRITE}
    [M] 'function int i_input_add(GIOChannel*, int, GInputFunction, void*)'    {g_input_add}
    [M] 'function int i_input_add_full(GIOChannel*, int, int, GInputFunction, void*)'    {g_input_add_full}
    [M] 'function int i_input_add_poll(int, int, int, GInputFunction, void*)'    {g_input_add_poll}
    [M] 'function GIOChannel* i_io_channel_new(int)'    {g_io_channel_new}
    [M] 'function int i_io_channel_read_block(GIOChannel*, void*, int)'    {g_io_channel_read_block}
    [M] 'function int i_io_channel_write_block(GIOChannel*, void*, int)'    {g_io_channel_write_block}
    [M] 'function int i_istr_cmp(gconstpointer, gconstpointer)'    {g_istr_cmp}
    [M] 'function int i_istr_equal(gconstpointer, gconstpointer)'    {g_istr_equal}
    [M] 'function guint i_istr_hash(gconstpointer)'    {g_istr_hash}
```

**Comment by dequis** [comment]
Ugh.

Any particular motivation for this change? Did it finally become a problem?

**Comment by ailin-nemui** [comment]
just doing clean-up work. what's your opinion? better delay indefinitely :-)?

**Comment by ailin-nemui** [comment]
merging this after discussion with dequis who doesn't like it. But it's better to fix mistakes. We had one break already in the past with ssl->tls

**Pull request merged**
