### PR TITLE
fix test on Big Endian 64bit, due to pointer size mismatch

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
the code was wrong (casting a small size ptr to a larger one)

**Comment by ailin-nemui** [comment]
reported via debian build infrastructure / @rhonda

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dwfreed** [comment]
The fix makes sense, but why are you making a block here? I'd just put the variable declaration at the top of the function with the others.

**Comment by ailin-nemui** [comment]
it's just a test.. but you wouldn't want any access to the temporary buf_len, could lead to wrong usage

**Pull request merged**
