### PR TITLE
Route notices intended for channels into the channel

### PR DESCRIPTION
**Pull request by ailin-nemui**
This works for

    -ChanServ(ChanServ@services.)- [#irssi] Welcome to #irssi.

or

    -bI(~xxx@unaffiliated/account)- [#irssi] your message is restrained

etc.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
good idea

**Comment by dwfreed** [comment]
1. In my case, I have a permanent query window with ChanServ (and other services), intentionally so that all ChanServ messages go there; this bypasses that
2. As an oper, I don't want random users to be able to flood the channel window of their choice just by forming their message in a special way

**Comment by dequis** [comment]
+1 for the setting, I thought about it but failed to come up with use cases where it's undesirable.

Regarding the latter, that's probably worth thinking about a bit more, maybe check what restrictions are set by other clients that implement this behavior. Channel membership of the source nick?

**Comment by ailin-nemui** [comment]
we talked about it on IRC but ChanServ, a prime offender, is often not on channel

**Comment by ailin-nemui** [comment]
@irssi/developers

**Pull request merged**
