### PR TITLE
Getaddrinfo v6 flag

### PR DESCRIPTION
**Pull request by LemonBoy**
Stacked on top of #408.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
I am not sure how this would affect reconnects after interface configuration changes (IPv6 added etc)

**Comment by LemonBoy** [comment]
The currently behaviour is the worst case scenario with this. 10/10 would merge.

**Comment by ailin-nemui** [comment]
currently  you can use -4 or -6 to choose which server you want to connect to, but if you do not even retrieve those IPs then that won't be possible anymore

**Comment by LemonBoy** [comment]
If there are no AAAA records that means there's no interface capable of connecting to an ipv6 address, so the `-6` is going to fail anyway.
With this patch we just avoid returning an unsupported address.

**Comment by ailin-nemui** [comment]
let's try this then

**Pull request merged**
