### PR TITLE
Save a patch from the Flyspray oblivion, plus a nice unrelated commit to make everyone (un)happy

### PR DESCRIPTION
**Pull request by LemonBoy**
http://bugs.irssi.org/index.php?do=details&task_id=904

### CODE REVIEW

**Comment by dequis** [comment]
I don't think that's what backport means.

Also nice unrelated commit.

**Comment by dequis** [comment]
:heart:

That patch is really useless in practice, but, whatever. It's certainly more correct.

LGTM

**Comment by dequis** [comment]
Actually, can you use `i_isblank()` instead?

From `common.h`:

```c
/* ctype.h isn't safe with chars, use our own instead */
...
#define i_isblank(x) isblank((int) (unsigned char) (x))
```

**Comment by ailin-nemui** [comment]
maybe you shouldn't mix different commits like this

**Comment by LemonBoy** [comment]
Usingb`i_isblank` on a `unichar` would bring an unwanted downcast, introducing a bug we'll probably hear people complain about in ~10 years.

The commits are related, both target the same function and don't introduce any functional change.

**Comment by dequis** [comment]
Lemon is right, so i'm merging this.

**Pull request merged**
