### PR TITLE
Check for abi compatibility using github actions

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
wip

**Comment by dequis** [comment]
Noice

**Comment by ailin-nemui** [comment]
this will use abigail's abidiff so it's probably not bullet proof all but at least should stop us from big mistakes

**Comment by ailin-nemui** [comment]
seems to be doing it's thing

https://github.com/irssi/irssi/actions/runs/84183959

@irssi/developers

**Pull request merged**
