### PR TITLE
Add better support for numeric 489 ERR_SECUREONLYCHAN along with a print format

### PR DESCRIPTION
**Pull request by mh-source**
This is a first attempt at adding support for numeric 489 as ERR_SECUREONLYCHAN in addition to the already supported ERR_VOICENEEDED. To fix my own submitted issue #1193 

It adds a new event_489 handler and the format string 'joinerror_secure_only'. but it is not unlikely i have missed some other (required) details for adding a numeric and format string.

It is ofcourse tested (at least for ERR_SECUREONLYCHAN, i dont know where it is used as ERR_VOICENEEDED so cant test triggering that) and "it works on my computer" :-)

modified:   src/fe-common/irc/fe-events-numeric.c
modified:   src/fe-common/irc/module-formats.c
modified:   src/fe-common/irc/module-formats.h

### CODE REVIEW

**Comment by ailin-nemui** [comment]
thanks :-)

**Comment by mh-source** [comment]
Now the failed tests have been fixed and I tested the ERR_VOICENEEDED on undernet with success. Hopefully no more loose ends.

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dequis** [comment]
Sure, looks solid. We should do something about those `clang-format off` at some point later (shouldn't block this, good to keep them as a marker)

**Pull request merged**
