### PR TITLE
Implement priority on the matched lines for /hilight

### LINKED ISSUE #1228: hilight does not respect -priority arg
I have the following `hilight` configuration

```
 /hilight
...
19:34    3 ccc  -line -priority 20 -color %G -actcolor %g
19:34    4 ddd  -line -priority 1 -color %p -actcolor %p
19:34    5 fff  -line -priority 100 -color %k -actcolor %k
```

**Actual:**
After receiving a message containing all the matching words like `ccc ddd fff` the message always gets highlighted according to the first positional match in the config.

**Expected:**
highlight the message according to the `-priority` arg.

### PR DESCRIPTION
**Pull request by vague666**
Since the original use case wasn't broken(Fixes #1228) this adds more functionality instead :)

### CODE REVIEW

**Comment by ailin-nemui** [comment]
maybe you forgot to set some variable to NULL?

**Comment by vague666** [comment]
Only possible var is tmprec, maybe I am remembering wrong that it is NULL when declared?

**Comment by ailin-nemui** [comment]
now it doesn't crash anymore :-) only the code formatting is left to clean up to confirm to the new standard

**Comment by vague666** [comment]
Maybe I do too much perl and forget that not all languages initialize variables :)

**Comment by ailin-nemui** [comment]
@irssi/developers ?

**Pull request merged**
