### PR TITLE
Revert "Removed the obsolete SQUERY and SERVLIST commands"

### PR DESCRIPTION
**Pull request by ailin-nemui**
This reverts commit 4beebe3238dda96efd4c3a0a6f6002ad5afc96e7.

### CODE REVIEW

**Comment by LemonBoy** [comment]
This belongs to a script

**Comment by ailin-nemui** [comment]
These are rfc commands,  idk why they should be removed

**Comment by LemonBoy** [comment]
The help files in the commit you mentioned state they only work for IRCNet, is this still true?

**Comment by ailin-nemui** [comment]
They work on any network running ircd (like ircnet)  or any network which chooses to implement them. Rfc documents don't seem any worse than "ircv3" to me...

**Comment by LemonBoy** [comment]
I was trying to undestand if those commands were effectively obsolete and/or exclusively for ircnet ( as the documentation leads to believe). Lgtm as long as the ‎misunderstanding is cleared up in the doc

**Pull request merged**
