### PR TITLE
ensure cap_supported is existent yet

### LINKED ISSUE #839: some crash
https://pastebin.com/raw/715P0EAr

> KindOne

> I /think/ I found a bug in git head/master when trying to connect, https://pastebin.com/raw/715P0EAr ;; irssi 1.1-gf8fbc1e1a (20180205 2229)

*dx edit: copying contents of pastebin here*

```
$ cat /downloads/bt.log 
No stack.
Starting program: /usr/bin/irssi 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb73d9b40 (LWP 16496)]

Thread 1 "irssi" received signal SIGSEGV, Segmentation fault.
0xb7b109d1 in g_hash_table_iter_next () from /lib/i386-linux-gnu/libglib-2.0.so.0
#0  0xb7b109d1 in g_hash_table_iter_next () from /lib/i386-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#1  0xb73ded2e in perl_irc_server_fill_hash (hv=0x621724, server=<optimized out>) at Irc.xs:42
        av = <optimized out>
        hv_ = 0x6b9260
        tmp = <optimized out>
        iter = {dummy1 = 0x24, dummy2 = 0x665aa0, dummy3 = 0x2326113, dummy4 = 6707872, dummy5 = 0, dummy6 = 0x7e}
        key_ = 0x6
        val_ = 0x0
#2  0x004ae33f in irssi_bless_iobject (type=732, chat_type=66, object=0x629860) at perl-common.c:139
        rec = 0x5b7ee0
        stash = 0x5b3020
        hv = 0x621724
        __func__ = "irssi_bless_iobject"
#3  0xb73ec414 in perl_text_dest_fill_hash (hv=0x6b95d0, dest=0xbfffeff8) at UI.xs:59
No locals.
#4  0x004ae3f9 in irssi_bless_plain (stash=0x4cb131 "Irssi::UI::TextDest", object=0xbfffeff8) at perl-common.c:153
        fill_func = 0xb73ec3a0 <perl_text_dest_fill_hash>
        hv = 0x6b95d0
#5  0x004b0aa6 in perl_call_signal (args=<optimized out>, signal_id=<optimized out>, func=<optimized out>, script=<optimized out>)
    at perl-signals.c:296
        perlarg = <optimized out>
        sp = 0x547b50
        rec = 0x531444 <perl_signal_args+5508>
        sv = <optimized out>
        saved_args = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
        av = <optimized out>
        arg = <optimized out>
        n = 0
#6  sig_func (p1=<optimized out>, p2=0x66f470, p3=0x6c0590, p4=0x0, p5=0x0, p6=0x0) at perl-signals.c:363
        rec = <optimized out>
        args = {0xbfffeff8, 0x66f470, 0x6c0590, 0x0, 0x0, 0x0}
#7  0x004a2291 in signal_emit_real (rec=rec@entry=0x560a30, params=params@entry=3, va=<optimized out>, 
    va@entry=0xbfffee58 "\370\357\377\277p\364f", first_hook=0x56b720) at signals.c:242
        arglist = {0xbfffeff8, 0x66f470, 0x6c0590, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x565cf0
        hook = 0x6ba6b0
        prev_emitted_hook = 0x565d10
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#8  0x004a281b in signal_emit_id (signal_id=304, params=3) at signals.c:304
        rec = 0x560a30
        va = 0xbfffee58 "\370\357\377\277p\364f"
        __func__ = "signal_emit_id"
#9  0x0045b83a in print_line (dest=dest@entry=0xbfffeff8, text=text@entry=0x6ba1b0 "Looking up \004cchat.freenode.net\004c")
    at printtext.c:182
        theme = <optimized out>
        str = 0x66f470 "\004\071/-\004g!\004\071/-\004g \004cIrssi:\004c Looking up \004cchat.freenode.net\004c"
        tmp = <optimized out>
        stripped = 0x6c0590 "-!- Irssi: Looking up chat.freenode.net"
        __func__ = "print_line"
#10 0x0045c069 in printformat_module_dest_charargs (module=0x4b799d "fe-common/core", dest=0xbfffeff8, formatnum=41, arglist=0xbfffeed0)
    at printtext.c:80
        theme = <optimized out>
        str = 0x6ba1b0 "Looking up \004cchat.freenode.net\004c"
#11 0x0045c0d8 in printformat_module_dest_args (module=0x4b799d "fe-common/core", dest=0xbfffeff8, formatnum=41, va=0xbffff044 "p\005l")
    at printtext.c:58
        arglist = {0x6c0570 "chat.freenode.net", 0x0, 
          0x52006e "\024\203\005P\016LJ\016PO\016@T\016LB\016PH\016@P\016LD\016PD\016TA\016XG\016\\D\016`L\016@I\n\016\024C\303\016\020A\306\016\fA\307\016\bA\305\016\004D\vC\016\024F\303\016\020A\306\016\fA\307\016\bA\305\016\004", 
          0x426219 <statusbar_redraw+969> "\213D$(\213T$$\203\304\020\211\020\203\304,[^_]\303f\220;W\034\017\205p\377\377\377\351\004\376\377\377\211\357\211\362)\302\001щO\030\351\212\375\377\377f\220\061\355븉Ǎv", 0x595f40 "H_Y", 0x0, 
          0x2 <error: Cannot access memory at address 0x2>, 0x8 <error: Cannot access memory at address 0x8>, 0x5935d0 "\300\346a", 
          0x5bf2f0 "\001"}
        buffer = "\251\016\261\267\000\220R\000\000\000\000\000(\357\377\277,\357\377\277\275RI\000X#Y\000\000\000\000\000(\357\377\277,\357\377\277\360\362[\000\000\000\000\000\000\000\004\000\307HF\000`\230b\000\000\000\004\000iRI\000`\230b\000\370\357\377\277 \360\377\277`\230b\000\000\000\000\000\300_K\000\334\002\000\000\tHF\000\000\220R\000\370\357\377\277 \360\377\277`\230b\000i_E\000`\230b\000\000\000\000\000\000\000\004\000\221\"J\000\360\362[\000`\230b\000\333^E\000\000\220R\000\370\357\377\277D\360\377\277\000\220R\000\236_E\000\370\357\377\277`\230b", '\000' <repeats 11 times>, "\004\000\360\362[\000\360\362[\000`\230b"
        formats = <optimized out>
#12 0x0045c1a2 in printformat_module_args (va=0xbffff044 "p\005l", formatnum=41, level=262144, target=0x0, server=0x629860, 
    module=0x4b799d "fe-common/core") at printtext.c:101
        dest = {window = 0x5bf2f0, server = 0x629860, server_tag = 0x6c16f0 "Freenode", target = 0x0, nick = 0x0, address = 0x0, 
          level = 262144, hilight_priority = 0, hilight_color = 0x0, flags = 0}
#13 printformat_module (module=0x4b799d "fe-common/core", server=0x629860, target=0x0, level=262144, formatnum=41) at printtext.c:110
        va = 0xbffff044 "p\005l"
#14 0x00452c86 in sig_server_looking (server=0x629860) at fe-server.c:353
No locals.
#15 0x004a2291 in signal_emit_real (rec=rec@entry=0x565cf0, params=params@entry=1, va=<optimized out>, va@entry=0xbffff0f8 "`\230b", 
    first_hook=0x54d440) at signals.c:242
        arglist = {0x629860, 0x0, 0x0, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x5455b0
        hook = 0x565d10
        prev_emitted_hook = 0x5455d0
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#16 0x004a279b in signal_emit (signal=0x4bb43a "server looking", params=1) at signals.c:286
        rec = 0x565cf0
        va = 0xbffff0f8 "`\230b"
        signal_id = <optimized out>
        __func__ = "signal_emit"
#17 0x0049bf81 in server_start_connect (server=0x629860) at servers.c:431
        connect_address = <optimized out>
        fd = {4, 5}
        __func__ = "server_start_connect"
#18 0x004704b1 in irc_server_connect (server=0x629860) at irc-servers.c:346
        __func__ = "irc_server_connect"
#19 0x0049b067 in server_connect (conn=0x66f260) at servers.c:347
        proto = 0x546c40
        server = 0x629860
#20 0x004a5d7f in cmd_connect (data=0x69db10 "chat.freenode.net") at chat-commands.c:168
        conn = 0x66f260
        server = <optimized out>
        rawlog_file = 0x0
#21 0x004a2291 in signal_emit_real (rec=rec@entry=0x5455b0, params=params@entry=3, va=<optimized out>, va@entry=0xbffff228 "\020\333i", 
    first_hook=0x5455d0) at signals.c:242
        arglist = {0x69db10, 0x0, 0x0, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x538e30
        hook = 0x5455d0
        prev_emitted_hook = 0x538e50
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#22 0x004a279b in signal_emit (signal=0x6c1710 "command connect", params=3) at signals.c:286
        rec = 0x5455b0
        va = 0xbffff228 "\020\333i"
        signal_id = <optimized out>
        __func__ = "signal_emit"
#23 0x0048b81b in parse_command (item=0x0, server=0x0, expand_aliases=<optimized out>, command=0x624f51 "connect chat.freenode.net")
    at commands.c:907
        newcmd = <optimized out>
        rec = <optimized out>
        alias = <optimized out>
        cmd = 0x6c1710 "command connect"
        orig = 0x69db00 "command connect"
        args = 0x69db10 "chat.freenode.net"
        oldcmd = 0x0
#24 event_command (line=0x624f51 "connect chat.freenode.net", server=0x0, item=0x0) at commands.c:953
        cmdchar = <optimized out>
        expand_aliases = <optimized out>
        __func__ = "event_command"
#25 0x004a2291 in signal_emit_real (rec=rec@entry=0x538e30, params=params@entry=3, va=<optimized out>, va@entry=0xbffff308 "POb", 
    first_hook=0x569780) at signals.c:242
        arglist = {0x624f50, 0x0, 0x0, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x58ad10
        hook = 0x538e50
        prev_emitted_hook = 0x58ad30
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#26 0x004a279b in signal_emit (signal=0x4b3283 "send command", params=3) at signals.c:286
        rec = 0x538e30
        va = 0xbffff308 "POb"
        signal_id = <optimized out>
        __func__ = "signal_emit"
#27 0x0041d629 in key_send_line () at gui-readline.c:493
        history = <optimized out>
        str = 0x624f50 "/connect chat.freenode.net"
        add_history = <optimized out>
#28 0x004a2291 in signal_emit_real (rec=rec@entry=0x58ad10, params=params@entry=3, va=<optimized out>, va@entry=0xbffff3e8 "\006\033L", 
    first_hook=0x58ad30) at signals.c:242
        arglist = {0x4c1b06, 0x0, 0x58aca0, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x55dfd0
        hook = 0x58ad30
        prev_emitted_hook = 0x55e2a0
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#29 0x004a279b in signal_emit (signal=0x5ccd30 "key send_line", params=3) at signals.c:286
        rec = 0x58ad10
        va = 0xbffff3e8 "\006\033L"
        signal_id = <optimized out>
        __func__ = "signal_emit"
#30 0x0045a9a6 in sig_multi (data=0x605240 "check_replaces;send_line", gui_data=0x0) at keyboard.c:717
        info = 0x58aca0
        list = 0x62f400
        tmp = 0x62f404
        p = 0x4c1b06 ""
        str = 0x5ccd30 "key send_line"
#31 0x004a2291 in signal_emit_real (rec=rec@entry=0x55dfd0, params=params@entry=3, va=<optimized out>, va@entry=0xbffff4c8 "@R`", 
    first_hook=0x55e2a0) at signals.c:242
        arglist = {0x605240, 0x0, 0x55df90, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x58fa90
        hook = 0x55e2a0
        prev_emitted_hook = 0x58fb80
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#32 0x004a279b in signal_emit (signal=0x5b9510 "key multi", params=3) at signals.c:286
        rec = 0x55dfd0
        va = 0xbffff4c8 "@R`"
        signal_id = <optimized out>
        __func__ = "signal_emit"
#33 0x00459902 in key_emit_signal (key=<optimized out>, key=<optimized out>, keyboard=<optimized out>) at keyboard.c:585
        consumed = <optimized out>
        str = 0x5b9510 "key multi"
#34 0x0045b480 in key_pressed (keyboard=0x584fb0, key=0xbffff56c "^M") at keyboard.c:672
        rec = <optimized out>
        combo = 0x5b9510 "key multi"
        first_key = <optimized out>
        consumed = <optimized out>
        __func__ = "key_pressed"
#35 0x0041cc44 in sig_gui_key_pressed (keyp=0xd) at gui-readline.c:448
        now = {tv_sec = 1517953249, tv_usec = 676328}
        key = 13
        str = "^M\000\267p\372X\000y3K\000\311,\264\267\000\220R"
        ret = <optimized out>
#36 0x004a2291 in signal_emit_real (rec=rec@entry=0x58fa90, params=params@entry=1, va=<optimized out>, va@entry=0xbffff638 "\r", 
    first_hook=0x58fb80) at signals.c:242
        arglist = {0xd, 0x0, 0x0, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x0
        hook = 0x58fb80
        prev_emitted_hook = 0x0
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#37 0x004a279b in signal_emit (signal=0x4b3379 "gui key pressed", params=1) at signals.c:286
        rec = 0x58fa90
        va = 0xbffff638 "\r"
        signal_id = <optimized out>
        __func__ = "signal_emit"
#38 0x0041e832 in sig_input () at gui-readline.c:852
        key = <optimized out>
        i = 0
#39 0x0049318b in irssi_io_invoke (source=0x56ee00, condition=G_IO_IN, data=0x582d90) at misc.c:51
        rec = 0x582d90
        icond = <optimized out>
#40 0xb7b22ac4 in g_main_context_dispatch () from /lib/i386-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#41 0xb7b22ed9 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#42 0xb7b22f84 in g_main_context_iteration () from /lib/i386-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#43 0x00417c07 in main (argc=<optimized out>, argv=<optimized out>) at irssi.c:333
        version = 0
        options = {{long_name = 0x4b7dfa "version", short_name = 118 'v', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x531f0c <version>, 
            description = 0x4b54d3 "Display Irssi version", arg_description = 0x0}, {long_name = 0x0, short_name = 0 '\000', flags = 0, 
            arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        loglev = <optimized out>
```

### PR DESCRIPTION
**Pull request by ailin-nemui**
attempt to fix #839 

@realkindone can you test this?

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by LemonBoy** [comment]
I think the dictionary should be initialized but empty

**Comment by ailin-nemui** [comment]
what do you mean ?

**Comment by LemonBoy** [comment]
With this patch if `cap_supported` is `NULL` no perl hash is created at all.

**Comment by ailin-nemui** [comment]
you mean it should always be created? idk if it matters. it would match more closely the C side where you decided to not always create a table

**Comment by LemonBoy** [comment]
Since you're the resident perl expert feel free to pick the solution that's more perl-ish/convenient for the API consumer.

**Comment by RealKindOne** [comment]
Looks like its fixed. Thanks.

**Comment by ailin-nemui** [comment]
thanks for reporting

**Pull request merged**
