### PR TITLE
Introduce send_data_func for interception my modules.

### PR DESCRIPTION
**Pull request by stapelberg**
This is for the RobustIRC module we talked about in #231,
which now lives at https://github.com/robustirc/irssi-robustirc

### CODE REVIEW

**Comment by ailin-nemui** [comment]
not to inflict too much additional pain on you; I understand that you want to reuse the existing IRC protocol implementation. I'm not sure about the best strategy because your whole project feels like a hack to me. On the other hand it would be cool if irssi can be the place for such a playground.

I haven't looked into it, but how feasible would it be to do the redirection on a g_io_channel level? Then you shouldn't need this special case in the IRC parser here

**Comment by stapelberg** [comment]
@ailin-nemui I think http://web.mit.edu/ghudson/dev/nokrb/third/yelp/src/yelp-io-channel.c is an example of how this might work. I’ll take a look.

Note that while it might work, https://developer.gnome.org/glib/stable/glib-IO-Channels.html#GIOChannel forbids us from doing that, though: “A data structure representing an IO Channel. The fields should be considered private and should only be accessed with the following functions.”

So, merging this pull request might be the cleaner solution after all :).

**Comment by dequis** [comment]
I'm surprised they even document stuff like GIOFuncs when the only way to set those is to access private members.

**Comment by ailin-nemui** [comment]
I suspect the documentation might be talking about consumers of GIOChannels, not about implementors

**Comment by stapelberg** [comment]
With https://github.com/robustirc/irssi-robustirc/commit/a176acafe4724c6205e3599f3a1ba690e96c3729, this pull request becomes obsolete.

Thanks for the hint, @ailin-nemui!

**Pull request closed without merging**
