### PR TITLE
fix level uninitialised

### PR DESCRIPTION
**Pull request by ailin-nemui**
Credit to OSS-Fuzz

### CODE REVIEW

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by dequis** [comment]
Not really sure how to judge this change from the originally-intended-behavior perspective tbh... From the C side I guess it's fine?

**Comment by ailin-nemui** [comment]
you can compare with https://github.com/irssi/irssi/blob/master/src/fe-common/core/fe-messages.c#L169 maybe

**Comment by ailin-nemui** [comment]
@irssi/developers

**Review by dequis — APPROVED** [review]

**Pull request merged**
