### PR TITLE
Postpone server cleanup until after unref

### PR DESCRIPTION
**Pull request by ailin-nemui**
Add a new signal, server destroyed, that is supposed to run the clean up
tasks of server disconnected. This is so that some structures will stay
around longer.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
this PR needs to be checked for any adverse side effects that could be caused by adding the additional signal and moving the work

**Comment by horgh** [comment]
If we didn't want to change/add signals, we could alternatively return if `mserver == NULL` in `flood.c` I think. Is it important to run `flood_newmsg()` if the server is disconnected?

**Comment by ailin-nemui** [comment]
yes you're probably right 

lthough I think trying to improve the signals and refcounting is a good overall direction. 

(thanks to your test framework!) try removing https://github.com/irssi/irssi/pull/802/files#diff-3ef538dbbcaf339ceb86081bf85cd41fR118 the fatality increase here, I believe all hash table warnings are bugs. (but maybe they would be fixed by returning from flood_newmsg, I didn't check)

**Comment by horgh** [comment]
Ah yeah. If I try returning early there instead of the fix in this branch, there are a bunch of hash_table_lookup assertion failures and a broken looking message in the status at the time of disconnect:

```
21:38 -!- Irssi: critical g_hash_table_lookup: assertion 'hash_table != NULL' failed
21:38 -!- Irssi: critical g_hash_table_lookup: assertion 'hash_table != NULL' failed
21:38 < :#test> t
21:38 -!- Irssi: critical g_hash_table_lookup: assertion 'hash_table != NULL' failed
21:38 -!- Irssi: critical g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

So the fix here is better!

**Comment by ailin-nemui** [comment]
@irssi/developers tagging this for merge unless you have a better suggestion or would prefer to discuss further

**Comment by dequis** [comment]
I haven't looked at this one at all and it sounds fiddlier than average, give me some time.

**Comment by ailin-nemui** [comment]
@dequis any updates?

**Comment by ailin-nemui** [comment]
@irssi/developers @dequis if you don't want to check this any more I suggest we merge it

**Comment by dequis** [comment]
I poked this for a while and failed to break it, so, yay? Not that i'm particularly inspired today.

Should this be mentioned in `docs/signals.txt`?

**Comment by ailin-nemui** [comment]
I think it's better to leave undocumented for now

**Pull request merged**
