### PR TITLE
properly record line info on empty lines

### PR DESCRIPTION
**Pull request by ailin-nemui**
another attempt at fixing #873 GL#31 #907 

it's basically the same as before with a special case for trackbar.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
anything which prints an empty string was previously ignored. now, it starts a new line. this might cause issues -- already identified the trackbar one last time, but it's unknown if there are other special cases which need consideration

**Comment by dequis** [comment]
>it's unknown if there are other special cases which need consideration

This makes the `g_slice_new0` solution look more attractive tbh

**Comment by ailin-nemui** [comment]
but that doesn't record the proper time and level. we can do both, this one to fix a missing thing and new0 to avoid uninitialised memory

**Comment by ailin-nemui** [comment]
@irssi/developers

**Pull request merged**
