### PR TITLE
Add tests for mode parsing

### PR DESCRIPTION
**Pull request by horgh**
This branches off of the changes in #766. I've moved the test program to a new tests subdirectory, switched to using GLib's testing framework, and changed the tests to be table driven.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
can you cherry pick bc059f2 only in this PR?

**Comment by horgh** [comment]
I did that and edited it so tests would pass. By itself it would fail as it was testing the mode parsing PR. If we merge this first I can rebase that PR on it.

**Comment by ailin-nemui** [comment]
it's ok if the tests fail as this means we have a bug....

**Comment by horgh** [comment]
Well if we merged this with it failing, Travis would start failing everywhere! That seems unhelpful. I left TODO comments with what can be updated by the other PR.

**Pull request closed without merging**
