### PR TITLE
revert the change to perl-common that would stop it from creating ghost chatnets

### LINKED ISSUE #1112: Irssi::chatnets returns raw pointers instead of objects
reported by @bw1 @vague666 

https://github.com/irssi/scripts.irssi.org/blob/86bec20f067151896418bffd01161ab0baed012f/Test/notes/irssi.log#L1-L2

### PR DESCRIPTION
**Pull request by ailin-nemui**
fixes #1112

### CODE REVIEW

**Comment by vague666** [comment]
Works

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by vague666** [comment]
Don't know if it can be rewritten somehow, this is the output without patch
```
aug 23 22:44:56 $VAR1 = \bless( {
aug 23 22:44:56                    'chat_type' => 'IRC',
aug 23 22:44:56                    '_irssi' => '94811764237312',
aug 23 22:44:56                    'nick' => '',
aug 23 22:44:56                    'autosendcmd' => '',
aug 23 22:44:56                    'own_host' => '',
aug 23 22:44:56                    'realname' => '',
aug 23 22:44:56                    'username' => '',
aug 23 22:44:56                    'type' => 'CHATNET',
aug 23 22:44:56                    'name' => 'QuakeNet'
aug 23 22:44:56                  }, 'Irssi::Irc::Chatnet' );
aug 23 22:44:56 **$VAR2 = \'94811764236112'; // this is a SILC network**
aug 23 22:44:56 $VAR3 = \bless( {
aug 23 22:44:56                    'username' => 'vague',
aug 23 22:44:56                    'name' => 'freenode',
aug 23 22:44:56                    'type' => 'CHATNET',
aug 23 22:44:56                    'nick' => 'vague',
aug 23 22:44:56                    'autosendcmd' => '',
aug 23 22:44:56                    'own_host' => '',
aug 23 22:44:56                    'realname' => 'vague',
aug 23 22:44:56                    '_irssi' => '94811764235744',
aug 23 22:44:56                    'chat_type' => 'IRC'
aug 23 22:44:56                  }, 'Irssi::Irc::Chatnet' );
aug 23 22:44:56 $VAR4 = \bless( {
aug 23 22:44:56                    'autosendcmd' => '',
aug 23 22:44:56                    'nick' => '',
aug 23 22:44:56                    'realname' => '',
aug 23 22:44:56                    'own_host' => '',
aug 23 22:44:56                    'type' => 'CHATNET',
aug 23 22:44:56                    'name' => 'EFNet',
aug 23 22:44:56                    'username' => '',
aug 23 22:44:56                    'chat_type' => 'IRC',
aug 23 22:44:56                    '_irssi' => '94811764232480'
aug 23 22:44:56                  }, 'Irssi::Irc::Chatnet' );
aug 23 22:44:56 $VAR5 = \bless( {
aug 23 22:44:56                    'type' => 'CHATNET',
aug 23 22:44:56                    'name' => 'bitlbee',
aug 23 22:44:56                    'username' => '',
aug 23 22:44:56                    'realname' => '',
aug 23 22:44:56                    'own_host' => '',
aug 23 22:44:56                    'nick' => '',
aug 23 22:44:56                    '_irssi' => '94811764220176',
aug 23 22:44:56                    'chat_type' => 'IRC'
aug 23 22:44:56                  }, 'Irssi::Irc::Chatnet' );
```

**Comment by ailin-nemui** [comment]
I think the bug was never released

**Pull request merged**
