### PR TITLE
ask user for ssl client cert password

### PR DESCRIPTION
**Pull request by TauPan**
Putting plaintext passwords in the irssi config might not conform to security requirements for some ssl client certificates.

see http://bugs.irssi.org/index.php?do=details&task_id=305&project=5

I'm not quite sure how to do this properly so I get a password prompt on the statusbar, which redraws afterwards.

Looking forward to your feedback on this.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
your code would block irssi while waiting for the password, which is not acceptable

**Comment by TauPan** [comment]
@ailin-nemui Oh. My use-case is logging into a single server with a configured ssl_cert on irssi startup.

You mean if the user receives a disconnect from a server irssi would block every other connection as well, while waiting for the password?

I certainly didn't anticipate that.

Since I'm not familiar with irssi's codebase I don't know how to proceed. If you see no other option to integrate this into irssi the proper way, I'm ok with closing this ticket.

**Comment by ailin-nemui** [comment]
I'm afraid the best we have come up so far with is to put it in /server -ssl_pass (which may get saved to your config)

for some related discussions general to passwords, you may also read issue #6 (and previously #103)

**Comment by ailin-nemui** [comment]
closing for inactivity

**Pull request closed without merging**
