### PR TITLE
do not use localtime result after other functions

### LINKED ISSUE #1207: day changed messages broken
date messed up somehow?
report by kinlo

https://spider.pfoe.be/weird-date-jump-irssi-2.png

Irssi 1.3-dev-296-g 964c067b

### PR DESCRIPTION
**Pull request by ailin-nemui**
Fixes #1207

### CODE REVIEW

**Comment by ailin-nemui** [comment]
not tested, might fix #1207

**Comment by ailin-nemui** [comment]
works for kinlo

**Comment by ailin-nemui** [comment]
@irssi/developers

**Comment by vague666** [comment]
Works for me too although I did not test without the diff to see if I experienced similar problems as kinlo

**Pull request merged**
