### PR TITLE
Rewrite some faulty logic handling the saved channels.

### PR DESCRIPTION
**Pull request by LemonBoy**
To the future self
Less prose in commit message
Write haikus instead
.

### CODE REVIEW

**Comment by dequis** [comment]
You should also compare the chatnet attribute, otherwise this would mess up channels with the same name in different networks.

I'd pass the whole CHANNEL_SETUP_REC to the compare function.

**Comment by LemonBoy** [comment]
Yup, didn't think about that. PR updated

**Comment by ailin-nemui** [comment]
thanks for digging into this, LemonBoy. @FastLizard4 can you test this?

**Comment by FastLizard4** [comment]
Tested this by checking out the 0.8.17 tag and applying this pull request as a patch.  Unfortunately, it did not fix the bug - I was still able to get irssi to munge the configuration file by deleting a network (without removing its channels) and then for another network adding a channel and deleting another (irssi deleted the wrong line entirely from the config file).

Worth noting that #313 does effectively mitigate the problem, based on my testing.

**Comment by LemonBoy** [comment]
Can you please provide a minimal config file and a list of commands to reproduce the problem ?

**Comment by FastLizard4** [comment]
Looks like this will reliably reproduce the problem for me.  Here's the initial config file I used:
```
servers = (
  { address = "irc.dal.net"; chatnet = "DALnet"; port = "6667"; },
  { address = "irc.efnet.org"; chatnet = "EFNet"; port = "6667"; },
  { address = "irc.esper.net"; chatnet = "EsperNet"; port = "6667"; },
  {
    address = "chat.freenode.net";
    chatnet = "Freenode";
    port = "6667";
  },
  { 
    address = "irc.gamesurge.net";
    chatnet = "GameSurge";
    port = "6667";
  },
  { address = "eu.irc6.net"; chatnet = "IRCnet"; port = "6667"; },
  { address = "open.ircnet.net"; chatnet = "IRCnet"; port = "6667"; },
  {
    address = "irc.ircsource.net";
    chatnet = "IRCSource";
    port = "6667";
  },
  { address = "irc.netfuze.net"; chatnet = "NetFuze"; port = "6667"; },
  { address = "irc.oftc.net"; chatnet = "OFTC"; port = "6667"; },
  {
    address = "irc.quakenet.org";
    chatnet = "QuakeNet";
    port = "6667";
  },
  { address = "irc.rizon.net"; chatnet = "Rizon"; port = "6667"; },
  { address = "silc.silcnet.org"; chatnet = "SILC"; port = "706"; },
  {
    address = "irc.undernet.org";
    chatnet = "Undernet";
    port = "6667";
  },
  { 
    address = "irc.example.com";
    chatnet = "netone";
    port = "6667";
    use_ssl = "no";
    ssl_verify = "no";
  },
  { 
    address = "irc.sample.com";
    chatnet = "nettwo";
    port = "6667";
    use_ssl = "no";
    ssl_verify = "no";
  }
);

chatnets = {
  DALnet = {
    type = "IRC";
    max_kicks = "4";
    max_msgs = "20";
    max_whois = "30";
  };
  EFNet = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "4";
    max_whois = "1";
  };
  EsperNet = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "4";
    max_whois = "1";
  };
  Freenode = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "4";
    max_whois = "1";
  };
  GameSurge = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "1";
    max_whois = "1";
  };
  IRCnet = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "1";
    max_whois = "1";
  };
  IRCSource = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "4";
    max_whois = "1";
  };
  NetFuze = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "1";
    max_whois = "1";
  };
  OFTC = { type = "IRC"; max_kicks = "1"; max_msgs = "1"; max_whois = "1"; };
  QuakeNet = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "1";
    max_whois = "1";
  };
  Rizon = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "1";
    max_whois = "1";
  };
  SILC = { type = "SILC"; };
  Undernet = {
    type = "IRC";
    max_kicks = "1";
    max_msgs = "1";
    max_whois = "1";
  };
  netone = { type = "IRC"; };
  nettwo = { type = "IRC"; };
};

channels = (
  { name = "#lobby"; chatnet = "EsperNet"; autojoin = "No"; },
  { name = "#freenode"; chatnet = "Freenode"; autojoin = "No"; },
  { name = "#irssi"; chatnet = "Freenode"; autojoin = "No"; },
  { name = "#gamesurge"; chatnet = "GameSurge"; autojoin = "No"; },
  { name = "#irssi"; chatnet = "IRCNet"; autojoin = "No"; },
  { name = "#ircsource"; chatnet = "IRCSource"; autojoin = "No"; },
  { name = "#netfuze"; chatnet = "NetFuze"; autojoin = "No"; },
  { name = "#oftc"; chatnet = "OFTC"; autojoin = "No"; },
  { name = "silc"; chatnet = "SILC"; autojoin = "No"; },
  { name = "#one"; chatnet = "netone"; },
  { name = "#two"; chatnet = "nettwo"; },
  { name = "#three"; chatnet = "netone"; },
  { name = "#four"; chatnet = "netone"; },
  { name = "#five"; chatnet = "netone"; },
  { name = "#six"; chatnet = "netone"; },
  { name = "#seven"; chatnet = "nettwo"; },
  { name = "#eight"; chatnet = "nettwo"; },
  { name = "#nine"; chatnet = "nettwo"; },
  { name = "#ten"; chatnet = "nettwo"; },
  {
    name = "#testtest";
    chatnet = "netone";
    autojoin = "yes";
    password = "testtest";
  },
  {
    name = "#testtest2";
    chatnet = "netone";
    autojoin = "yes";
    password = "testtest";
  },
  { name = "#testtest3"; chatnet = "netone"; autojoin = "yes"; }
);

aliases = {
  ATAG = "WINDOW SERVER";
  ADDALLCHANS = "SCRIPT EXEC foreach my \\$channel (Irssi::channels()) { Irssi::command(\"CHANNEL ADD -auto \\$channel->{name} \\$channel->{server}->{tag} \\$channel-$
  B = "BAN";
  BACK = "AWAY";
  BANS = "BAN";
  BYE = "QUIT";
  C = "CLEAR";
  CALC = "EXEC - if command -v bc >/dev/null 2>&1\\; then printf '%s=' '$*'\\; echo '$*' | bc -l\\; else echo bc was not found\\; fi";
  CHAT = "DCC CHAT";
  CUBES = "SCRIPT EXEC Irssi::active_win->print(\"%_bases\", MSGLEVEL_CLIENTCRAP) \\; Irssi::active_win->print( do { join '', map { \"%x0\\${_}0\\$_\" } '0'..'9','A'.$
  DATE = "TIME";
  DEHIGHLIGHT = "DEHILIGHT";
  DESCRIBE = "ACTION";
  DHL = "DEHILIGHT";
  EXEMPTLIST = "MODE $C +e";
  EXIT = "QUIT";
  GOTO = "SCROLLBACK GOTO";
  HIGHLIGHT = "HILIGHT";
  HL = "HILIGHT";
  HOST = "USERHOST";
  INVITELIST = "MODE $C +I";
  J = "JOIN";
  K = "KICK";
  KB = "KICKBAN";
  KN = "KNOCKOUT";
  LAST = "LASTLOG";
  LEAVE = "PART";
  M = "MSG";
  MUB = "UNBAN *";
  N = "NAMES";
  NMSG = "^MSG";
  P = "PART";
  Q = "QUERY";
  RESET = "SET -default";
  RUN = "SCRIPT LOAD";
  SAY = "MSG *";
  SB = "SCROLLBACK";
  SBAR = "STATUSBAR";
  SIGNOFF = "QUIT";
  SV = "MSG * Irssi $J ($V) - http://www.irssi.org";
  T = "TOPIC";
  UB = "UNBAN";
  UMODE = "MODE $N";
  UNSET = "SET -clear";
  W = "WHO";
  WC = "WINDOW CLOSE";
  WG = "WINDOW GOTO";
  WJOIN = "JOIN -window";
  WI = "WHOIS";
  WII = "WHOIS $0 $0";
  WL = "WINDOW LIST";
  WN = "WINDOW NEW HIDDEN";
  WQUERY = "QUERY -window";
  WW = "WHOWAS";
  1 = "WINDOW GOTO 1";
  2 = "WINDOW GOTO 2";
  3 = "WINDOW GOTO 3";
  4 = "WINDOW GOTO 4";
  5 = "WINDOW GOTO 5";
  6 = "WINDOW GOTO 6";
  7 = "WINDOW GOTO 7";
  8 = "WINDOW GOTO 8";
  9 = "WINDOW GOTO 9";
  10 = "WINDOW GOTO 10";
  11 = "WINDOW GOTO 11";
  12 = "WINDOW GOTO 12";
  13 = "WINDOW GOTO 13";
  14 = "WINDOW GOTO 14";
  15 = "WINDOW GOTO 15";
  16 = "WINDOW GOTO 16";
  17 = "WINDOW GOTO 17";
  18 = "WINDOW GOTO 18";
  19 = "WINDOW GOTO 19";
  20 = "WINDOW GOTO 20";
  21 = "WINDOW GOTO 21";
  22 = "WINDOW GOTO 22";
  23 = "WINDOW GOTO 23";
  24 = "WINDOW GOTO 24";
  25 = "WINDOW GOTO 25";
  26 = "WINDOW GOTO 26";
  27 = "WINDOW GOTO 27";
  28 = "WINDOW GOTO 28";
  29 = "WINDOW GOTO 29";
  30 = "WINDOW GOTO 30";
  31 = "WINDOW GOTO 31";
  32 = "WINDOW GOTO 32";
  33 = "WINDOW GOTO 33";
  34 = "WINDOW GOTO 34";
  35 = "WINDOW GOTO 35";
  36 = "WINDOW GOTO 36";
  37 = "WINDOW GOTO 37";
  38 = "WINDOW GOTO 38";
  39 = "WINDOW GOTO 39";
  40 = "WINDOW GOTO 40";
  41 = "WINDOW GOTO 41";
  42 = "WINDOW GOTO 42";
  43 = "WINDOW GOTO 43";
  44 = "WINDOW GOTO 44";
  45 = "WINDOW GOTO 45";
  46 = "WINDOW GOTO 46";
  47 = "WINDOW GOTO 47";
  48 = "WINDOW GOTO 48";
  49 = "WINDOW GOTO 49";
  50 = "WINDOW GOTO 50";
  51 = "WINDOW GOTO 51";
  52 = "WINDOW GOTO 52";
  53 = "WINDOW GOTO 53";
  54 = "WINDOW GOTO 54";
  55 = "WINDOW GOTO 55";
  56 = "WINDOW GOTO 56";
  57 = "WINDOW GOTO 57";
  58 = "WINDOW GOTO 58";
  59 = "WINDOW GOTO 59";
  60 = "WINDOW GOTO 60";
  61 = "WINDOW GOTO 61";
  62 = "WINDOW GOTO 62";
  63 = "WINDOW GOTO 63";
  64 = "WINDOW GOTO 64";
  65 = "WINDOW GOTO 65";
  66 = "WINDOW GOTO 66";
  67 = "WINDOW GOTO 67";
  68 = "WINDOW GOTO 68";
  69 = "WINDOW GOTO 69";
  70 = "WINDOW GOTO 70";
  71 = "WINDOW GOTO 71";
  72 = "WINDOW GOTO 72";
  73 = "WINDOW GOTO 73";
  74 = "WINDOW GOTO 74";
  75 = "WINDOW GOTO 75";
  76 = "WINDOW GOTO 76";
  77 = "WINDOW GOTO 77";
  78 = "WINDOW GOTO 78";
  79 = "WINDOW GOTO 79";
  80 = "WINDOW GOTO 80";
  81 = "WINDOW GOTO 81";
  82 = "WINDOW GOTO 82";
  83 = "WINDOW GOTO 83";
  84 = "WINDOW GOTO 84";
  85 = "WINDOW GOTO 85";
  86 = "WINDOW GOTO 86";
  87 = "WINDOW GOTO 87";
  88 = "WINDOW GOTO 88";
  89 = "WINDOW GOTO 89";
  90 = "WINDOW GOTO 90";
  91 = "WINDOW GOTO 91";
  92 = "WINDOW GOTO 92";
  93 = "WINDOW GOTO 93";
  94 = "WINDOW GOTO 94";
  95 = "WINDOW GOTO 95";
  96 = "WINDOW GOTO 96";
  97 = "WINDOW GOTO 97";
  98 = "WINDOW GOTO 98";
  99 = "WINDOW GOTO 99";
};

statusbar = {

  items = {

    barstart = "{sbstart}";
    barend = "{sbend}";

    topicbarstart = "{topicsbstart}";
    topicbarend = "{topicsbend}";

    time = "{sb $Z}";
    user = "{sb {sbnickmode $cumode}$N{sbmode $usermode}{sbaway $A}}";

    window = "{sb $winref:$tag/$itemname{sbmode $M}}";
    window_empty = "{sb $winref{sbservertag $tag}}";

    prompt = "{prompt $[.15]itemname}";
    prompt_empty = "{prompt $winname}";

    topic = " $topic";
    topic_empty = " Irssi v$J - http://www.irssi.org";

    lag = "{sb Lag: $0-}";
    act = "{sb Act: $0-}";
    more = "-- more --";
  };

  default = {

    window = {

      disabled = "no";
      type = "window";
      placement = "bottom";
      position = "1";
      visible = "active";

      items = {
        barstart = { priority = "100"; };
        time = { };
        user = { };
        window = { };
        window_empty = { };
        lag = { priority = "-1"; };
        act = { priority = "10"; };
        more = { priority = "-1"; alignment = "right"; };
        barend = { priority = "100"; alignment = "right"; };
      };
    };

    window_inact = {

      type = "window";
      placement = "bottom";
      position = "1";
      visible = "inactive";

      items = {
        barstart = { priority = "100"; };
        window = { };
        window_empty = { };
        more = { priority = "-1"; alignment = "right"; };
        barend = { priority = "100"; alignment = "right"; };
      };
    };

    prompt = {

      type = "root";
      placement = "bottom";
      position = "100";
      visible = "always";

      items = {
        prompt = { priority = "-1"; };
        prompt_empty = { priority = "-1"; };
        input = { priority = "10"; };
      };
    };

    topic = {

      type = "root";
      placement = "top";
      position = "1";
      visible = "always";

      items = {
        topicbarstart = { priority = "100"; };
        topic = { };
        topic_empty = { };
        topicbarend = { priority = "100"; alignment = "right"; };
      };
    };
  };
};
settings = {
  core = {
    real_name = "FastLizard4";
    user_name = "fastlizard4";
    nick = "fastlizard4";
  };
  "fe-text" = { actlist_sort = "refnum"; };
};
```

I loaded the above config file into irssi, then ran these commands:

```
/network remove nettwo
/channel add #test netone
/channel remove #testtest3 netone
/save
```

Which yielded the following result for me:

```diff
--- config.1    2015-12-08 14:00:23.000000000 -0800
+++ config      2015-12-08 14:00:46.000000000 -0800
@@ -119,7 +119,6 @@
     max_whois = "1";
   };
   netone = { type = "IRC"; };
-  nettwo = { type = "IRC"; };
 };
 
 channels = (
@@ -139,7 +138,6 @@
   { name = "#five"; chatnet = "netone"; },
   { name = "#six"; chatnet = "netone"; },
   { name = "#seven"; chatnet = "nettwo"; },
-  { name = "#eight"; chatnet = "nettwo"; },
   { name = "#nine"; chatnet = "nettwo"; },
   { name = "#ten"; chatnet = "nettwo"; },
   {
@@ -154,7 +152,8 @@
     autojoin = "yes";
     password = "testtest";
   },
-  { name = "#testtest3"; chatnet = "netone"; autojoin = "yes"; }
+  { name = "#testtest3"; chatnet = "netone"; autojoin = "yes"; },
+  { name = "#test"; chatnet = "netone"; }
 );
 
 aliases = {
```

**Comment by LemonBoy** [comment]
I can't reproduce that result at all.
Just to be safe, try reverting to 8217147a805af081010578b0dcd7fe42fede1425 and cherry picking this over that.

**Comment by FastLizard4** [comment]
I am also unable to reproduce the result if I revert to 8217147 and cherry pick this patchset over... but I am also unable to reproduce the result if I revert to 8217147 and *don't* apply this pull request at all.

**Comment by LemonBoy** [comment]
I can't reproduce your result even by reverting to df1df75ca2cc461360e336ce83052366002b1b8a and then cherry picking this patch over.

**Comment by FastLizard4** [comment]
Now I can't either.  Maybe I missed something in my reproduction steps?  Let me do some more testing.

**Comment by FastLizard4** [comment]
Okay, yes, apparently I did miss something: It's important to save after removing the network and before running the channel commands:

```
/network remove nettwo
/save
/channel add #test netone
/channel remove #testtest3 netone
/save
```

**Comment by FastLizard4** [comment]
Okay, some more weirdness - it seems that it sometimes doesn't work after just starting irssi.  If the first reproduction attempt fails, though, I simply restore the configuration file its initial state, do `/reload`, then attempt to reproduce again and it works.

**Comment by LemonBoy** [comment]
The latest commit should put a definitive end to this problem

**Comment by FastLizard4** [comment]
Yup, tested by applying pull request on top of 8217147 - and it works!  Thanks!

**Comment by dequis** [comment]
New code looks good.

I could nitpick about the naming of `compare_channel_name` which doesn't really describe what it does anymore, but it's a static function so it doesn't really matter.

**Comment by ailin-nemui** [comment]
does the same logic wrt servers also need to be replaced?

**Comment by LemonBoy** [comment]
Good catch Nei, the code handling the server section was still using the indices, ready to corrupt some configuration files.

**Comment by ailin-nemui** [comment]
was an honest question but it's good if you conclude it needs fixing. should we be using `g_strcmp0` everywhere? does that save some explicit NULL checks? Please use explicit `== 0` / `!= 0` code as is almost everywhere else in Irssi

**Pull request merged**
