### PR TITLE
Parse GEN_IPADD records in subjectAltName.

### PR DESCRIPTION
**Pull request by LemonBoy**
Needs testing, don't have time right now to do so.
Fixes [bdo#583544](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=583544)

### CODE REVIEW

**Comment by dequis** [comment]
Crazy stuff. It sounds like the sort of thing openssl should be handling for us, and it really would be better to find a way to solve this with less code, not more.

**Comment by dequis** [comment]
```c
static gboolean irssi_ssl_verify(SSL *ssl, SSL_CTX *ctx, const char* hostname, int port, X509 *cert, SERVER_REC *server, TLS_REC *tls_rec)
{
	long result;

	result = SSL_get_verify_result(ssl);
	if (result != X509_V_OK) {
		g_warning("Could not verify TLS servers certificate: %s", X509_verify_cert_error_string(result));
		return FALSE;
	} else if (! irssi_ssl_verify_hostname(cert, hostname)){
		return FALSE;
	}
	return TRUE;
}
```

Sounds like SSL_get_verify_result is OK but our extra checks are failing.

**Comment by ahf** [comment]
We should ask ourselves if we really want this feature and, if we do want it, whether it should be protected by a flag somehow that is disabled by default.

**Comment by dequis** [comment]
Are certificates issued to IP addresses something that is usually unsupported everywhere?

Hmm I wonder if this is the sort of thing where you could throw a CSR with fields the CA doesn't recognize, have it signed because the CA sucks, and pass validation

Also, from the ticket:

> 0: it's not from an irc server, but that doesn't matter here.
>   Also, details redacted since it's not available on the public internet
>   anyway.

So... no real use case? Just submitting bugs for the sake of annoying devs?

**Comment by dequis** [comment]
Heh that makes my last comment sound bad. Context:

>16:50 < TheLemonMan> I'll close the openssl pr, we'd better to entirely offload the verification process to openssl
>16:50 < TheLemonMan> any objection?

**Pull request closed without merging**
