### PR TITLE
Copy Perl signal arguments prior to running callbacks

### LINKED ISSUE #1233: memory corruption in Perl stack during signal emission
https://github.com/irssi/irssi/blob/master/src/perl/perl-signals.c#L209

crash on SvOK

reported by @RealKindOne

### PR DESCRIPTION
**Pull request by ailin-nemui**
Might fix #1233

### CODE REVIEW

**Comment by dequis** [comment]
I guess the croaks around lines 100-102 might leak memory?

**Comment by ailin-nemui** [comment]
that would seem likely...

**Comment by ailin-nemui** [comment]
it would probably suffice to copy the arguments before the callback, what do you think would be better?

https://github.com/irssi/irssi/blob/e0292665c1adef5a1d8893555f4810dc5b72ffc6/src/perl/perl-signals.c#L206

**Comment by dequis** [comment]
Yeah, maybe, if that makes the diff more minimal and you understand the scope of the issue. I'm not terribly confident about this one, the perl API is a lot.

**Comment by ailin-nemui** [comment]
@irssi/developers

**Review by dequis — APPROVED** [review]
I hope there's no secret croaking anywhere

**Pull request merged**
