### PR TITLE
enable self-message support

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by ailin-nemui** [comment]
without this, znc doesn't display your other client PMs for instance

**Comment by ailin-nemui** [comment]
(note that this spec has been removed from IRCv3 but they have no usable replacement)

**Comment by ailin-nemui** [comment]
there is no way to know which messages are echoes and which are from other connected clients :-)

**Comment by dequis** [comment]
Yeah, so if you disable local echo entirely and display every incoming message, you don't need to know that.

But it gets perceived as higher latency when sending messages, can be weird for people used to it being instant (or can be seen as a feature confirming messages got to the server!). It'd be nice as an off-by-default setting.

**Pull request merged**
