### PR TITLE
[WIP] Native Proxy support for Irssi

### PR DESCRIPTION
**Pull request by hawken93**
See the changes in TODO. There are warnings produced while running it and there are also some usage of "\_\_attribute__((\__packed__));"
Nevertheless, I would like feedback :)

### CODE REVIEW

**Comment by dgl** [comment]
Just mentioned on #irssi that it would be cool to have support for external proxies (ala ssh's `ProxyCommand`). That way we don't need to support every proxy type but people can still experiment. (To be clear this would be in addition to the proxy types here as those seem reasonable to have in core).

**Comment by vague666** [comment]
Just an opinion, but -host shouldn't be used to specify server to connect to since it's used to specify the interface to bind to elsewhere in irssi(/server), no need to add to the confusion

**Comment by ahf** [comment]
Good point, thanks :-)

**Comment by dequis** [comment]
This lives in https://github.com/irssi/irssi/tree/orphaned/native-proxy now

**Pull request closed without merging**
